// Dados carregados por api/universidade/admin.js — gerado a partir do documento auditado
export const questionsData = [
  {
    "id": "GEO-001",
    "disciplina": "Geografia",
    "pergunta": "Qual destes locais portugueses existe mesmo?",
    "opcaoA": "Jardim das Pichas Murchas",
    "opcaoB": "Jardim dos Tomates Secos",
    "opcaoC": "Jardim dos Bigodes Tristes",
    "opcaoD": "Jardim das Barbas Caídas",
    "respostaCorreta": "A) Jardim das Pichas Murchas",
    "curiosidade": "O Jardim das Pichas Murchas existe mesmo em Lisboa, na freguesia de São Vicente. O nome nasceu de uma brincadeira popular e acabou por ficar na toponímia local."
  },
  {
    "id": "GEO-002",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Venda da Gaita",
    "opcaoB": "Feira do Trombone",
    "opcaoC": "Aldeia da Sanfona",
    "opcaoD": "Monte do Saxofone",
    "respostaCorreta": "A) Venda da Gaita",
    "curiosidade": "Venda da Gaita é uma localidade real no concelho de Pedrógão Grande e aparece frequentemente nas listas dos nomes mais curiosos de Portugal."
  },
  {
    "id": "GEO-003",
    "disciplina": "Geografia",
    "pergunta": "Qual é o maior país do mundo em área?",
    "opcaoA": "Canadá",
    "opcaoB": "Rússia",
    "opcaoC": "China",
    "opcaoD": "Estados Unidos",
    "respostaCorreta": "B) Rússia",
    "curiosidade": "A Rússia ocupa cerca de 17 milhões de km² e atravessa 11 fusos horários."
  },
  {
    "id": "GEO-004",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem uma bandeira que não é retangular?",
    "opcaoA": "Nepal",
    "opcaoB": "Butão",
    "opcaoC": "Sri Lanka",
    "opcaoD": "Laos",
    "respostaCorreta": "A) Nepal",
    "curiosidade": "A bandeira do Nepal é formada por dois triângulos sobrepostos e é única entre os países soberanos."
  },
  {
    "id": "GEO-005",
    "disciplina": "Geografia",
    "pergunta": "Qual destas cidades é capital da Austrália?",
    "opcaoA": "Sydney",
    "opcaoB": "Melbourne",
    "opcaoC": "Canberra",
    "opcaoD": "Perth",
    "respostaCorreta": "C) Canberra",
    "curiosidade": "Canberra foi construída de propósito para evitar rivalidades entre Sydney e Melbourne."
  },
  {
    "id": "GEO-006",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países não tem saída para o mar?",
    "opcaoA": "Bolívia",
    "opcaoB": "Peru",
    "opcaoC": "Equador",
    "opcaoD": "Chile",
    "respostaCorreta": "A) Bolívia",
    "curiosidade": "A Bolívia perdeu a sua costa para o Chile na Guerra do Pacífico, no século XIX."
  },
  {
    "id": "GEO-007",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Cabrões",
    "opcaoB": "Carneiros Felizes",
    "opcaoC": "Ovelhas do Norte",
    "opcaoD": "Burros Unidos",
    "respostaCorreta": "A) Cabrões",
    "curiosidade": "Cabrões é uma localidade real do concelho de Santo Tirso e costuma aparecer em listas de topónimos insólitos portugueses."
  },
  {
    "id": "GEO-008",
    "disciplina": "Geografia",
    "pergunta": "Qual destas ilhas pertence a Portugal?",
    "opcaoA": "La Gomera",
    "opcaoB": "El Hierro",
    "opcaoC": "Porto Santo",
    "opcaoD": "Tenerife",
    "respostaCorreta": "C) Porto Santo",
    "curiosidade": "Porto Santo faz parte do arquipélago da Madeira e é conhecida pela sua praia de areia dourada com cerca de 9 km."
  },
  {
    "id": "GEO-010",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é atravessado por mais fusos horários?",
    "opcaoA": "Estados Unidos",
    "opcaoB": "Rússia",
    "opcaoC": "França",
    "opcaoD": "Canadá",
    "respostaCorreta": "C) França",
    "curiosidade": "Pode parecer estranho, mas devido aos seus territórios ultramarinos, a França é oficialmente o país com mais fusos horários (12, ou 13 se considerada a reivindicação na Antártida), superando a Rússia. É uma daquelas respostas que quase toda a gente erra à primeira."
  },
  {
    "id": "GEO-011",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Chiqueiro",
    "opcaoB": "Pocilga Feliz",
    "opcaoC": "Lama Seca",
    "opcaoD": "Buraco Fundo",
    "respostaCorreta": "A) Chiqueiro",
    "curiosidade": "Chiqueiro existe mesmo em Portugal e é uma pequena localidade cujo nome costuma provocar gargalhadas quando aparece em listas de topónimos curiosos."
  },
  {
    "id": "GEO-012",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem o maior número de ilhas do mundo?",
    "opcaoA": "Indonésia",
    "opcaoB": "Filipinas",
    "opcaoC": "Suécia",
    "opcaoD": "Japão",
    "respostaCorreta": "C) Suécia",
    "curiosidade": "A Suécia possui cerca de 267 mil ilhas, embora apenas uma pequena parte seja habitada."
  },
  {
    "id": "GEO-013",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Picha",
    "opcaoB": "Pichota",
    "opcaoC": "Picholas",
    "opcaoD": "Picharada",
    "respostaCorreta": "A) Picha",
    "curiosidade": "Existe uma localidade chamada Picha, no concelho de Pedrógão Grande. O nome é antigo e não tem a origem que a maioria das pessoas imagina."
  },
  {
    "id": "GEO-014",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem a maior população do mundo atualmente?",
    "opcaoA": "Índia",
    "opcaoB": "China",
    "opcaoC": "Estados Unidos",
    "opcaoD": "Indonésia",
    "respostaCorreta": "A) Índia",
    "curiosidade": "Em 2023 a Índia ultrapassou oficialmente a China em população."
  },
  {
    "id": "GEO-016",
    "disciplina": "Geografia",
    "pergunta": "Qual é o lago com maior volume de água doce do planeta?",
    "opcaoA": "Lago Vitória",
    "opcaoB": "Lago Superior",
    "opcaoC": "Lago Baikal",
    "opcaoD": "Lago Tanganica",
    "respostaCorreta": "C) Lago Baikal",
    "curiosidade": "O Baikal, na Rússia, contém cerca de 20% da água doce líquida não congelada do planeta."
  },
  {
    "id": "GEO-017",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países faz fronteira com Portugal?",
    "opcaoA": "França",
    "opcaoB": "Andorra",
    "opcaoC": "Espanha",
    "opcaoD": "Marrocos",
    "respostaCorreta": "C) Espanha",
    "curiosidade": "Portugal apenas tem uma fronteira terrestre."
  },
  {
    "id": "GEO-018",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Cabeço de Vide",
    "opcaoB": "Pescoço de DVD",
    "opcaoC": "Orelha de CD",
    "opcaoD": "Nariz de Vinil",
    "respostaCorreta": "A) Cabeço de Vide",
    "curiosidade": "Cabeço de Vide pertence ao concelho de Fronteira e é conhecida pelas suas águas termais."
  },
  {
    "id": "GEO-019",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem maior área?",
    "opcaoA": "Alemanha",
    "opcaoB": "França",
    "opcaoC": "Itália",
    "opcaoD": "Espanha",
    "respostaCorreta": "B) França",
    "curiosidade": "Mesmo sem contar com territórios ultramarinos, França continua a ser o maior país da União Europeia em área."
  },
  {
    "id": "GEO-020",
    "disciplina": "Geografia",
    "pergunta": "Qual destas cidades está construída em dois continentes?",
    "opcaoA": "Atenas",
    "opcaoB": "Istambul",
    "opcaoC": "Roma",
    "opcaoD": "Viena",
    "respostaCorreta": "B) Istambul",
    "curiosidade": "Istambul é atravessada pelo estreito do Bósforo, separando Europa e Ásia."
  },
  {
    "id": "GEO-021",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Venda das Raparigas",
    "opcaoB": "Chão das Pias",
    "opcaoC": "Rua dos Cornos",
    "opcaoD": "Vale das Sogras",
    "respostaCorreta": "B) Chão das Pias",
    "curiosidade": "Chão das Pias existe mesmo no concelho de Ourém. O nome vem de antigas formações rochosas que lembravam pias naturais."
  },
  {
    "id": "GEO-022",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem mais vulcões ativos?",
    "opcaoA": "Japão",
    "opcaoB": "Chile",
    "opcaoC": "Indonésia",
    "opcaoD": "Islândia",
    "respostaCorreta": "C) Indonésia",
    "curiosidade": "A Indonésia tem mais de uma centena de vulcões ativos e situa-se no famoso Anel de Fogo do Pacífico."
  },
  {
    "id": "GEO-023",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem o formato geográfico mais semelhante a uma bota?",
    "opcaoA": "Grécia",
    "opcaoB": "Itália",
    "opcaoC": "Croácia",
    "opcaoD": "Albânia",
    "respostaCorreta": "B) Itália",
    "curiosidade": "É tão característico que basta um mapa sem nomes para quase toda a gente reconhecer Itália."
  },
  {
    "id": "GEO-024",
    "disciplina": "Geografia",
    "pergunta": "Qual é o rio mais longo do mundo segundo a maioria das medições atuais?",
    "opcaoA": "Amazonas",
    "opcaoB": "Nilo",
    "opcaoC": "Yangtzé",
    "opcaoD": "Mississippi",
    "respostaCorreta": "A) Amazonas",
    "curiosidade": "Durante muitos anos o Nilo foi considerado o mais longo. Estudos mais recentes atribuem essa posição ao Amazonas, embora ainda exista algum debate científico sobre o método de medição."
  },
  {
    "id": "GEO-025",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é completamente rodeado por Itália?",
    "opcaoA": "Andorra",
    "opcaoB": "Liechtenstein",
    "opcaoC": "San Marino",
    "opcaoD": "Mónaco",
    "respostaCorreta": "C) San Marino",
    "curiosidade": "San Marino é um dos países mais antigos do mundo e encontra-se totalmente rodeado por território italiano."
  },
  {
    "id": "GEO-026",
    "disciplina": "Geografia",
    "pergunta": "Qual destes distritos portugueses faz fronteira com Espanha?",
    "opcaoA": "Aveiro",
    "opcaoB": "Viseu",
    "opcaoC": "Portalegre",
    "opcaoD": "Leiria",
    "respostaCorreta": "C) Portalegre",
    "curiosidade": "Portalegre faz parte da extensa fronteira luso-espanhola, conhecida como \"A Raia\"."
  },
  {
    "id": "GEO-027",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem um dragão na sua bandeira?",
    "opcaoA": "País de Gales",
    "opcaoB": "Irlanda",
    "opcaoC": "Escócia",
    "opcaoD": "Inglaterra",
    "respostaCorreta": "A) País de Gales",
    "curiosidade": "Embora faça parte do Reino Unido, o País de Gales tem uma das bandeiras mais icónicas do mundo graças ao famoso dragão vermelho."
  },
  {
    "id": "GEO-028",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem a maior altitude média da Europa?",
    "opcaoA": "Suíça",
    "opcaoB": "Áustria",
    "opcaoC": "Andorra",
    "opcaoD": "Noruega",
    "respostaCorreta": "C) Andorra",
    "curiosidade": "Apesar de ser um país muito pequeno, Andorra tem uma altitude média superior à da Suíça."
  },
  {
    "id": "GEO-029",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Venda da Porca",
    "opcaoB": "Venda do Porco",
    "opcaoC": "Aldeia do Leitão",
    "opcaoD": "Monte do Toucinho",
    "respostaCorreta": "B) Venda do Porco",
    "curiosidade": "Venda do Porco existe mesmo no concelho de Leiria. Como muitos topónimos antigos, o nome está ligado a atividades rurais da época."
  },
  {
    "id": "GEO-030",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é atravessado simultaneamente pela Linha do Equador e pelo Meridiano de Greenwich?",
    "opcaoA": "Gabão",
    "opcaoB": "República do Congo",
    "opcaoC": "São Tomé e Príncipe",
    "opcaoD": "Gana",
    "respostaCorreta": "C) São Tomé e Príncipe",
    "curiosidade": "São Tomé e Príncipe é um dos raros países associados aos dois grandes referenciais geográficos, tornando-o uma excelente curiosidade para quizzes."
  },
  {
    "id": "POR-001",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente em português?",
    "opcaoA": "Esbardalhar",
    "opcaoB": "Escambardar",
    "opcaoC": "Espingalhar",
    "opcaoD": "Esgalhardar",
    "respostaCorreta": "A) Esbardalhar",
    "curiosidade": "\"Esbardalhar\" significa cair desamparadamente ou estragar algo por completo. É uma palavra reconhecida nos principais dicionários da língua portuguesa."
  },
  {
    "id": "POR-002",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Ir dar uma volta ao bilhar grande",
    "opcaoB": "Ir regar o cimento",
    "opcaoC": "Ir bater ao ferro frio",
    "opcaoD": "Ir dormir para a sombra do poste",
    "respostaCorreta": "A) Ir dar uma volta ao bilhar grande",
    "curiosidade": "\"Ir dar uma volta ao bilhar grande\" é uma forma popular e humorística de dizer que alguém morreu."
  },
  {
    "id": "POR-003",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Lambão",
    "opcaoB": "Lambosoide",
    "opcaoC": "Lambisco",
    "opcaoD": "Lambarudo",
    "respostaCorreta": "A) Lambão",
    "curiosidade": "\"Lambão\" descreve alguém muito guloso ou comilão e é uma palavra perfeitamente válida em português."
  },
  {
    "id": "POR-004",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras portuguesas tem origem árabe?",
    "opcaoA": "Almofada",
    "opcaoB": "Cadeira",
    "opcaoC": "Mesa",
    "opcaoD": "Janela",
    "respostaCorreta": "A) Almofada",
    "curiosidade": "Centenas de palavras portuguesas começam por \"al-\" precisamente por terem origem no árabe, como almofada, alface, aldeia e alfândega."
  },
  {
    "id": "POR-005",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Ficar a ver navios",
    "opcaoB": "Ficar a contar sardinhas",
    "opcaoC": "Ficar a apanhar relva",
    "opcaoD": "Ficar debaixo do sino",
    "respostaCorreta": "A) Ficar a ver navios",
    "curiosidade": "A expressão \"ficar a ver navios\" significa ficar desiludido ou sem aquilo que esperava."
  },
  {
    "id": "POR-006",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Escafeder",
    "opcaoB": "Escabedar",
    "opcaoC": "Escafundrar",
    "opcaoD": "Escapedrar",
    "respostaCorreta": "A) Escafeder",
    "curiosidade": "\"Escafeder-se\" significa fugir rapidamente ou desaparecer sem deixar rasto."
  },
  {
    "id": "POR-007",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras portuguesas designa uma chuva muito fraca?",
    "opcaoA": "Chuvisco",
    "opcaoB": "Chuveta",
    "opcaoC": "Chuvalho",
    "opcaoD": "Chuviscoide",
    "respostaCorreta": "A) Chuvisco",
    "curiosidade": "\"Chuvisco\" é o nome correto para uma precipitação muito leve e contínua."
  },
  {
    "id": "POR-008",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Meter a viola no saco",
    "opcaoB": "Guardar a guitarra no bolso",
    "opcaoC": "Dobrar o tambor",
    "opcaoD": "Enrolar a concertina",
    "respostaCorreta": "A) Meter a viola no saco",
    "curiosidade": "\"Meter a viola no saco\" significa desistir ou calar-se depois de perceber que perdeu a razão."
  },
  {
    "id": "POR-009",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Trambolho",
    "opcaoB": "Trambelho",
    "opcaoC": "Trambalhão",
    "opcaoD": "Trambelisco",
    "respostaCorreta": "A) Trambolho",
    "curiosidade": "\"Trambolho\" pode referir-se a um objeto grande, pesado ou pouco prático, mas também é usado para descrever alguém de forma bem-humorada."
  },
  {
    "id": "POR-010",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe e significa \"confusão ou desordem\"?",
    "opcaoA": "Alarido",
    "opcaoB": "Arreliaço",
    "opcaoC": "Algarito",
    "opcaoD": "Arregançoide",
    "respostaCorreta": "A) Alarido",
    "curiosidade": "\"Alarido\" descreve uma grande algazarra ou confusão, sendo uma palavra bastante antiga que continua presente no português atual."
  },
  {
    "id": "POR-011",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Estarrecido",
    "opcaoB": "Estarrecinho",
    "opcaoC": "Estarreço",
    "opcaoD": "Estarrecalho",
    "respostaCorreta": "A) Estarrecido",
    "curiosidade": "\"Estarrecido\" significa que sente grande medo, susto ou terror — usado em situações de choque ou pavor intenso."
  },
  {
    "id": "POR-012",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Pôr os bois à frente da carroça",
    "opcaoB": "Pôr as galinhas atrás do trator",
    "opcaoC": "Pôr o burro em cima da bicicleta",
    "opcaoD": "Pôr a cabra ao volante",
    "respostaCorreta": "A) Pôr os bois à frente da carroça",
    "curiosidade": "\"Pôr os bois à frente da carroça\" significa inverter a ordem lógica das coisas."
  },
  {
    "id": "POR-013",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Badameco",
    "opcaoB": "Badaroco",
    "opcaoC": "Badanelo",
    "opcaoD": "Badarrão",
    "respostaCorreta": "A) Badameco",
    "curiosidade": "\"Badameco\" é uma palavra usada para descrever alguém parvo, pateta ou pouco inteligente, normalmente em tom de brincadeira."
  },
  {
    "id": "POR-014",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Andar à nora",
    "opcaoB": "Andar ao escadote",
    "opcaoC": "Andar à pá",
    "opcaoD": "Andar ao candeeiro",
    "respostaCorreta": "A) Andar à nora",
    "curiosidade": "\"Andar à nora\" significa estar completamente perdido ou confuso."
  },
  {
    "id": "POR-015",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Fanfarrão",
    "opcaoB": "Fanfarrudo",
    "opcaoC": "Fanfarrentoide",
    "opcaoD": "Fanfarral",
    "respostaCorreta": "A) Fanfarrão",
    "curiosidade": "Um fanfarrão é alguém que gosta de se gabar ou exagerar as próprias capacidades."
  },
  {
    "id": "POR-016",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Quem tem boca vai a Roma",
    "opcaoB": "Quem tem pernas vai a Braga",
    "opcaoC": "Quem tem cotovelos vai a Faro",
    "opcaoD": "Quem tem barriga vai a Coimbra",
    "respostaCorreta": "A) Quem tem boca vai a Roma",
    "curiosidade": "Originalmente, esta expressão queria dizer que quem pergunta consegue encontrar o caminho."
  },
  {
    "id": "POR-017",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Zarolho",
    "opcaoB": "Zarolhudo",
    "opcaoC": "Zarolhão",
    "opcaoD": "Zarolhiceiro",
    "respostaCorreta": "A) Zarolho",
    "curiosidade": "\"Zarolho\" descreve alguém com estrabismo ou com um olho desalinhado. É uma palavra antiga que continua perfeitamente válida."
  },
  {
    "id": "POR-018",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Ficar em águas de bacalhau",
    "opcaoB": "Ficar em sopa de nabiças",
    "opcaoC": "Ficar em caldo verde",
    "opcaoD": "Ficar em arroz malandro",
    "respostaCorreta": "A) Ficar em águas de bacalhau",
    "curiosidade": "Quando algo \"fica em águas de bacalhau\", significa que acaba por não dar em nada."
  },
  {
    "id": "POR-019",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Patarata",
    "opcaoB": "Patareca",
    "opcaoC": "Patarica",
    "opcaoD": "Pataralha",
    "respostaCorreta": "A) Patarata",
    "curiosidade": "\"Patarata\" significa uma mentira, disparate ou conversa sem sentido."
  },
  {
    "id": "POR-020",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Estar com a corda ao pescoço",
    "opcaoB": "Estar com a meia na cabeça",
    "opcaoC": "Estar com a colher no bolso",
    "opcaoD": "Estar com a frigideira ao ombro",
    "respostaCorreta": "A) Estar com a corda ao pescoço",
    "curiosidade": "\"Estar com a corda ao pescoço\" significa estar numa situação difícil, normalmente por falta de dinheiro ou por estar sob grande pressão."
  },
  {
    "id": "POR-021",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Bugiganga",
    "opcaoB": "Bugalhanga",
    "opcaoC": "Buguelhenga",
    "opcaoD": "Bugarrada",
    "respostaCorreta": "A) Bugiganga",
    "curiosidade": "\"Bugiganga\" é uma palavra perfeitamente válida e refere-se a um objeto sem grande valor ou utilidade."
  },
  {
    "id": "POR-022",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Fazer uma vaquinha",
    "opcaoB": "Fazer uma cabrinha",
    "opcaoC": "Fazer um carneirinho",
    "opcaoD": "Fazer um porquinho",
    "respostaCorreta": "A) Fazer uma vaquinha",
    "curiosidade": "\"Fazer uma vaquinha\" significa juntar dinheiro entre várias pessoas para um objetivo comum."
  },
  {
    "id": "POR-023",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Catrefada",
    "opcaoB": "Catrapada",
    "opcaoC": "Catarrafada",
    "opcaoD": "Catrilhada",
    "respostaCorreta": "A) Catrefada",
    "curiosidade": "Uma \"catrefada\" significa uma grande quantidade de alguma coisa."
  },
  {
    "id": "POR-024",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Fanico",
    "opcaoB": "Fanecaço",
    "opcaoC": "Faniscalho",
    "opcaoD": "Fanecada",
    "respostaCorreta": "A) Fanico",
    "curiosidade": "\"Dar um fanico\" significa desmaiar ou sentir-se muito mal, sendo uma expressão muito usada em Portugal."
  },
  {
    "id": "POR-025",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Estar nas lonas",
    "opcaoB": "Estar nos lençóis",
    "opcaoC": "Estar nos tapetes",
    "opcaoD": "Estar nas cortinas",
    "respostaCorreta": "A) Estar nas lonas",
    "curiosidade": "\"Estar nas lonas\" significa estar sem dinheiro ou numa situação financeira complicada."
  },
  {
    "id": "POR-026",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Geringonça",
    "opcaoB": "Geringolha",
    "opcaoC": "Geringalha",
    "opcaoD": "Geringota",
    "respostaCorreta": "A) Geringonça",
    "curiosidade": "Originalmente, \"geringonça\" designava uma máquina ou objeto improvisado e pouco fiável."
  },
  {
    "id": "POR-027",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Rebeubéu, pardais ao ninho!",
    "opcaoB": "Chorar guardanapos ao vento",
    "opcaoC": "Enrolar bigodes na chaminé",
    "opcaoD": "Guardar patins no sótão da lua",
    "respostaCorreta": "A) Rebeubéu, pardais ao ninho!",
    "curiosidade": "\"Rebeubéu, pardais ao ninho!\" é uma expressão antiga que significa grande alvoroço ou confusão — ficou também conhecida por um programa de rádio/TV de Herman José com o mesmo nome."
  },
  {
    "id": "POR-028",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Não perceber patavina",
    "opcaoB": "Não perceber courgette",
    "opcaoC": "Não perceber nabiça",
    "opcaoD": "Não perceber feijoada",
    "respostaCorreta": "A) Não perceber patavina",
    "curiosidade": "\"Não perceber patavina\" significa não perceber absolutamente nada de determinado assunto."
  },
  {
    "id": "POR-029",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Alarve",
    "opcaoB": "Alarvão",
    "opcaoC": "Alarvudo",
    "opcaoD": "Alarvito",
    "respostaCorreta": "A) Alarve",
    "curiosidade": "\"Alarve\" designa uma pessoa rude ou mal-educada. Curiosamente, a palavra vem de \"árabe\", devido à forma como os mouros eram vistos na Idade Média."
  },
  {
    "id": "POR-030",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Badagaio",
    "opcaoB": "Badagalho",
    "opcaoC": "Badagueco",
    "opcaoD": "Badagarra",
    "respostaCorreta": "A) Badagaio",
    "curiosidade": "\"Badagaio\" significa tontura, vertigem ou crise nervosa — não uma pessoa magra, ao contrário do que às vezes se pensa."
  },
  {
    "id": "HIS-002",
    "disciplina": "História",
    "pergunta": "Qual destas profissões já existiu oficialmente na corte portuguesa?",
    "opcaoA": "Aparador de Barbas Reais",
    "opcaoB": "Limpador de Penicos do Rei",
    "opcaoC": "Afinador da Coroa",
    "opcaoD": "Dobrador Oficial de Capas",
    "respostaCorreta": "B) Limpador de Penicos do Rei",
    "curiosidade": "As cortes reais tinham dezenas de cargos que hoje parecem absurdos. O tratamento dos aposentos e dos utensílios pessoais do rei fazia parte da estrutura oficial da Casa Real."
  },
  {
    "id": "HIS-003",
    "disciplina": "História",
    "pergunta": "Qual destes animais recebeu uma patente militar durante a Segunda Guerra Mundial?",
    "opcaoA": "Um pombo-correio",
    "opcaoB": "Um urso",
    "opcaoC": "Um cão",
    "opcaoD": "Um burro",
    "respostaCorreta": "C) Um cão",
    "curiosidade": "Vários cães foram oficialmente condecorados por atos de coragem durante a guerra. Alguns receberam patentes honorárias e medalhas pelo serviço prestado."
  },
  {
    "id": "HIS-004",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido como \"O Venturoso\"?",
    "opcaoA": "D. Manuel I",
    "opcaoB": "D. João II",
    "opcaoC": "D. Dinis",
    "opcaoD": "D. Duarte",
    "respostaCorreta": "A) D. Manuel I",
    "curiosidade": "D. Manuel I reinou numa das épocas mais prósperas da História de Portugal, coincidindo com o auge dos Descobrimentos."
  },
  {
    "id": "HIS-005",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Dois países estiveram oficialmente em guerra durante menos de uma hora.",
    "opcaoB": "Um país declarou guerra ao Oceano Atlântico.",
    "opcaoC": "Um rei declarou guerra ao próprio exército.",
    "opcaoD": "Um país declarou guerra à Lua.",
    "respostaCorreta": "A) Dois países estiveram oficialmente em guerra durante menos de uma hora.",
    "curiosidade": "A Guerra Anglo-Zanzibar (1896) durou cerca de 38 minutos, sendo considerada a guerra mais curta da História."
  },
  {
    "id": "HIS-006",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Napoleão era invulgarmente baixo.",
    "opcaoB": "Os vikings usavam capacetes com cornos.",
    "opcaoC": "Cleópatra viveu mais perto da criação do iPhone do que da construção das pirâmides.",
    "opcaoD": "Nero tocava violino enquanto Roma ardia.",
    "respostaCorreta": "C) Cleópatra viveu mais perto da criação do iPhone do que da construção das pirâmides.",
    "curiosidade": "As Grandes Pirâmides tinham mais de 2.000 anos quando Cleópatra nasceu. Ela viveu cronologicamente muito mais perto dos dias de hoje do que da sua construção."
  },
  {
    "id": "HIS-007",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido por \"o Lavrador\"?",
    "opcaoA": "D. Dinis",
    "opcaoB": "D. João I",
    "opcaoC": "D. Sancho II",
    "opcaoD": "D. Pedro I",
    "respostaCorreta": "A) D. Dinis",
    "curiosidade": "Além de incentivar a agricultura, D. Dinis mandou plantar o Pinhal de Leiria, que viria mais tarde a fornecer madeira para a construção naval portuguesa."
  },
  {
    "id": "HIS-008",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um imperador romano nomeou o seu cavalo para um cargo político.",
    "opcaoB": "Um rei francês casou com uma estátua.",
    "opcaoC": "Um faraó proibiu as pirâmides.",
    "opcaoD": "Um Papa foi astronauta.",
    "respostaCorreta": "A) Um imperador romano nomeou o seu cavalo para um cargo político.",
    "curiosidade": "O imperador Calígula terá demonstrado intenção de nomear o seu cavalo Incitatus para um cargo elevado, embora os historiadores discutam se foi uma provocação política ou um facto literal."
  },
  {
    "id": "HIS-009",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses foi assassinado em Lisboa?",
    "opcaoA": "D. Carlos I",
    "opcaoB": "D. Manuel II",
    "opcaoC": "D. Luís I",
    "opcaoD": "D. Pedro V",
    "respostaCorreta": "A) D. Carlos I",
    "curiosidade": "D. Carlos I foi assassinado em 1908, no Terreiro do Paço, num dos acontecimentos mais marcantes da história da monarquia portuguesa."
  },
  {
    "id": "HIS-010",
    "disciplina": "História",
    "pergunta": "Qual destes países teve um \"Imperador\" que também era jogador de futebol profissional?",
    "opcaoA": "Brasil",
    "opcaoB": "Haiti",
    "opcaoC": "República Centro-Africana",
    "opcaoD": "México",
    "respostaCorreta": "C) República Centro-Africana",
    "curiosidade": "Jean-Bédel Bokassa autoproclamou-se imperador em 1976. Antes da carreira militar, chegou a praticar futebol, embora este seja um aspeto muito menos conhecido da sua vida."
  },
  {
    "id": "HIS-011",
    "disciplina": "História",
    "pergunta": "Qual destes impostos existiu mesmo em Portugal?",
    "opcaoA": "Imposto sobre barbas",
    "opcaoB": "Imposto das janelas",
    "opcaoC": "Imposto sobre chapéus de palha",
    "opcaoD": "Imposto dos galos",
    "respostaCorreta": "B) Imposto das janelas",
    "curiosidade": "O chamado \"imposto das janelas\" existiu em vários países europeus, incluindo Portugal. Como resultado, muitas casas antigas têm janelas tapadas com tijolo para evitar pagar mais imposto."
  },
  {
    "id": "HIS-012",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Os vikings usavam capacetes com cornos.",
    "opcaoB": "Napoleão media pouco mais de 1,50 m.",
    "opcaoC": "As bruxas de Salém foram queimadas.",
    "opcaoD": "Em Salém, os condenados foram enforcados, não queimados.",
    "respostaCorreta": "D) Em Salém, os condenados foram enforcados, não queimados.",
    "curiosidade": "Os vikings não usavam capacetes com cornos, Napoleão tinha uma altura normal para a época e, em Salém, os condenados foram enforcados, não queimados."
  },
  {
    "id": "HIS-013",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um exército perdeu uma batalha porque foi atacado por... coelhos.",
    "opcaoB": "Um país declarou guerra a aves marinhas.",
    "opcaoC": "A Austrália entrou em guerra contra emas.",
    "opcaoD": "Um castelo foi conquistado por ovelhas.",
    "respostaCorreta": "C) A Austrália entrou em guerra contra emas.",
    "curiosidade": "Em 1932, a Austrália lançou uma operação militar para controlar milhares de emas que destruíam plantações. Ficou conhecida como a Grande Guerra das Emas... e as emas \"ganharam\"."
  },
  {
    "id": "HIS-014",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido como \"O Justiceiro\"?",
    "opcaoA": "D. Pedro I",
    "opcaoB": "D. João II",
    "opcaoC": "D. Sancho I",
    "opcaoD": "D. Manuel II",
    "respostaCorreta": "A) D. Pedro I",
    "curiosidade": "D. Pedro I mandou perseguir os assassinos de Inês de Castro e, segundo a tradição, obrigou membros da corte a beijar a mão da rainha já depois de morta. Embora alguns detalhes sejam debatidos, a história tornou-se uma das mais famosas de Portugal."
  },
  {
    "id": "HIS-015",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um Papa foi julgado... depois de morrer.",
    "opcaoB": "Um faraó foi preso.",
    "opcaoC": "Um imperador vendeu o próprio país.",
    "opcaoD": "Um rei foi condenado por um tribunal moderno.",
    "respostaCorreta": "A) Um Papa foi julgado... depois de morrer.",
    "curiosidade": "No chamado Sínodo do Cadáver (897 d.C.), o corpo do Papa Formoso foi exumado, vestido com roupas papais e submetido a julgamento."
  },
  {
    "id": "HIS-016",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei português morreu por causa de uma queda de cavalo.",
    "opcaoB": "Um rei português morreu esmagado por uma árvore.",
    "opcaoC": "Um rei português morreu depois de comer um doce.",
    "opcaoD": "Um rei português morreu num desastre de carruagem.",
    "respostaCorreta": "D) Um rei português morreu num desastre de carruagem.",
    "curiosidade": "D. José I escapou, mas o acidente de carruagem em que seguia teve enorme impacto político e ajudou a desencadear acontecimentos ligados ao famoso Processo dos Távoras."
  },
  {
    "id": "HIS-017",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um soldado japonês continuou a combater muito tempo depois do fim da Segunda Guerra Mundial.",
    "opcaoB": "Um piloto aterrou na Lua por engano.",
    "opcaoC": "Um submarino atravessou o deserto.",
    "opcaoD": "Um tanque afundou um porta-aviões.",
    "respostaCorreta": "A) Um soldado japonês continuou a combater muito tempo depois do fim da Segunda Guerra Mundial.",
    "curiosidade": "Hiroo Onoda só se rendeu em 1974, porque acreditava que a guerra ainda não tinha terminado."
  },
  {
    "id": "HIS-018",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses morreu sem deixar descendentes legítimos, originando uma crise sucessória?",
    "opcaoA": "D. Sebastião",
    "opcaoB": "D. João IV",
    "opcaoC": "D. Afonso Henriques",
    "opcaoD": "D. Pedro IV",
    "respostaCorreta": "A) D. Sebastião",
    "curiosidade": "O desaparecimento de D. Sebastião abriu caminho para a crise de 1580 e para a União Ibérica."
  },
  {
    "id": "HIS-019",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "O presidente dos Estados Unidos já ficou preso numa banheira.",
    "opcaoB": "Um rei de Inglaterra perdeu uma guerra às pombas.",
    "opcaoC": "Um imperador chinês proibiu arroz.",
    "opcaoD": "Júlio César tinha medo de cavalos.",
    "respostaCorreta": "A) O presidente dos Estados Unidos já ficou preso numa banheira.",
    "curiosidade": "William Howard Taft era um homem de grande porte e ficou famoso por uma história em que alegadamente ficou preso na banheira da Casa Branca. Alguns historiadores discutem os detalhes, mas a história tornou-se lendária."
  },
  {
    "id": "HIS-020",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O Titanic foi o maior desastre marítimo da História.",
    "opcaoB": "Einstein era péssimo a Matemática.",
    "opcaoC": "A Grande Muralha da China é visível da Lua a olho nu.",
    "opcaoD": "Einstein era excelente a Matemática desde muito jovem.",
    "respostaCorreta": "D) Einstein era excelente a Matemática desde muito jovem.",
    "curiosidade": "O Titanic não foi o maior desastre marítimo em número de vítimas, Einstein era excelente a Matemática desde jovem e a Grande Muralha não é visível da Lua a olho nu."
  },
  {
    "id": "HIS-021",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "A Coca-Cola já foi vendida como medicamento.",
    "opcaoB": "A Nutella foi criada para alimentar soldados.",
    "opcaoC": "O ketchup nasceu em França.",
    "opcaoD": "A pizza foi inventada na Alemanha.",
    "respostaCorreta": "A) A Coca-Cola já foi vendida como medicamento.",
    "curiosidade": "Quando foi criada em 1886, a Coca-Cola era vendida nas farmácias como um tónico medicinal."
  },
  {
    "id": "HIS-022",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações sobre D. Afonso Henriques é verdadeira?",
    "opcaoA": "Foi armado cavaleiro aos 30 anos.",
    "opcaoB": "Foi preso pela própria mãe.",
    "opcaoC": "Foi rei de Espanha durante um dia.",
    "opcaoD": "Lutou numa cruzada no Japão.",
    "respostaCorreta": "B) Foi preso pela própria mãe.",
    "curiosidade": "Durante o conflito entre D. Teresa e D. Afonso Henriques, há relatos de que este chegou a ser detido por ordem da própria mãe antes de consolidar o seu poder."
  },
  {
    "id": "HIS-023",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei morreu porque um macaco o mordeu.",
    "opcaoB": "Um imperador morreu engasgado com uma cebola.",
    "opcaoC": "Um faraó morreu a jogar xadrez.",
    "opcaoD": "Um czar morreu a dançar.",
    "respostaCorreta": "A) Um rei morreu porque um macaco o mordeu.",
    "curiosidade": "O rei Alexandre da Grécia morreu em 1920 depois de desenvolver uma infeção causada pela mordida de um macaco durante uma tentativa de separar uma luta entre animais."
  },
  {
    "id": "HIS-024",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "As pirâmides foram construídas por escravos.",
    "opcaoB": "Júlio César nasceu por cesariana.",
    "opcaoC": "Os gladiadores lutavam sempre até à morte.",
    "opcaoD": "Muitos combates de gladiadores terminavam sem morte, por serem caros de treinar.",
    "respostaCorreta": "D) Muitos combates de gladiadores terminavam sem morte, por serem caros de treinar.",
    "curiosidade": "Os trabalhadores das pirâmides eram, em grande parte, artesãos e operários pagos; Júlio César não nasceu por cesariana; e muitos combates de gladiadores terminavam sem morte porque eram caros de treinar."
  },
  {
    "id": "HIS-025",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um urso serviu oficialmente no exército.",
    "opcaoB": "Um elefante foi eleito presidente.",
    "opcaoC": "Um pinguim comandou um navio.",
    "opcaoD": "Uma vaca recebeu um Nobel.",
    "respostaCorreta": "A) Um urso serviu oficialmente no exército.",
    "curiosidade": "Wojtek, um urso-pardo adotado por soldados polacos durante a Segunda Guerra Mundial, recebeu estatuto militar e ajudava a transportar caixas de munições."
  },
  {
    "id": "HIS-026",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses teve o cognome \"O Formoso\"?",
    "opcaoA": "D. Fernando I",
    "opcaoB": "D. Duarte",
    "opcaoC": "D. Sancho II",
    "opcaoD": "D. João III",
    "respostaCorreta": "A) D. Fernando I",
    "curiosidade": "D. Fernando I ficou conhecido como \"O Formoso\", embora o seu reinado tenha sido marcado por conflitos e instabilidade."
  },
  {
    "id": "HIS-027",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um homem sobreviveu às duas bombas atómicas do Japão.",
    "opcaoB": "Um piloto sobreviveu a cinco quedas na Lua.",
    "opcaoC": "Um marinheiro deu a volta ao mundo num submarino a remos.",
    "opcaoD": "Um astronauta perdeu-se em Marte.",
    "respostaCorreta": "A) Um homem sobreviveu às duas bombas atómicas do Japão.",
    "curiosidade": "Tsutomu Yamaguchi sobreviveu à bomba de Hiroshima, regressou a Nagasaki... e sobreviveu também à segunda explosão."
  },
  {
    "id": "HIS-028",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um exército perdeu porque confundiu o próprio barulho com um ataque inimigo.",
    "opcaoB": "Um castelo rendeu-se a um acordeão.",
    "opcaoC": "Um rei assinou um tratado com um golfinho.",
    "opcaoD": "Um país perdeu uma guerra porque acabou o café.",
    "respostaCorreta": "A) Um exército perdeu porque confundiu o próprio barulho com um ataque inimigo.",
    "curiosidade": "Na Batalha de Karánsebes (1788), tropas austríacas entraram em pânico e dispararam umas contra as outras após uma sequência de mal-entendidos e confusão durante a noite."
  },
  {
    "id": "HIS-029",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "O nome original do Mario era Jumpman.",
    "opcaoB": "Sonic chamava-se Blue Rabbit.",
    "opcaoC": "Pac-Man ia chamar-se Pizza Boy.",
    "opcaoD": "Link começou por ser um pirata.",
    "respostaCorreta": "A) O nome original do Mario era Jumpman.",
    "curiosidade": "Na sua primeira aparição em Donkey Kong (1981), Mario era conhecido apenas como Jumpman."
  },
  {
    "id": "HIS-030",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei morreu por rir demasiado.",
    "opcaoB": "Um Papa morreu a jogar cartas.",
    "opcaoC": "Um imperador morreu num concurso de dança.",
    "opcaoD": "Um faraó morreu a escorregar numa banana.",
    "respostaCorreta": "A) Um rei morreu por rir demasiado.",
    "curiosidade": "Segundo várias fontes históricas, o rei Martim I de Aragão morreu em 1410 após uma crise provocada por uma combinação de problemas digestivos e um ataque de riso desencadeado por uma piada do seu bobo da corte. A história é debatida nos detalhes, mas tornou-se uma das mortes mais insólitas atribuídas a um monarca."
  },
  {
    "id": "SCI-001",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais faz cocó em forma de cubo?",
    "opcaoA": "Coala",
    "opcaoB": "Wombat",
    "opcaoC": "Texugo",
    "opcaoD": "Castor",
    "respostaCorreta": "B) Wombat",
    "curiosidade": "O intestino do wombat comprime os excrementos de forma tão específica que eles saem... em cubos. Isto impede que rolem pelas encostas e ajuda a marcar território."
  },
  {
    "id": "SCI-002",
    "disciplina": "Ciência",
    "pergunta": "Qual destas partes do corpo humano continua a crescer durante praticamente toda a vida?",
    "opcaoA": "Dentes",
    "opcaoB": "Nariz e orelhas",
    "opcaoC": "Cotovelos",
    "opcaoD": "Rótulas",
    "respostaCorreta": "B) Nariz e orelhas",
    "curiosidade": "Na realidade, o que continua a mudar é sobretudo a cartilagem e a pele, dando a sensação de que o nariz e as orelhas \"crescem\" ao longo da vida."
  },
  {
    "id": "SCI-003",
    "disciplina": "Ciência",
    "pergunta": "Segundo astronautas, a que cheira o espaço?",
    "opcaoA": "Chocolate",
    "opcaoB": "Carne grelhada e metal queimado",
    "opcaoC": "Gasolina",
    "opcaoD": "Pipocas",
    "respostaCorreta": "B) Carne grelhada e metal queimado",
    "curiosidade": "Depois das caminhadas espaciais, vários astronautas descreveram um cheiro semelhante a metal quente, carne grelhada ou pólvora."
  },
  {
    "id": "SCI-004",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue sobreviver ao vácuo do espaço durante algum tempo?",
    "opcaoA": "Barata",
    "opcaoB": "Tardígrado",
    "opcaoC": "Escorpião",
    "opcaoD": "Polvo",
    "respostaCorreta": "B) Tardígrado",
    "curiosidade": "Os tardígrados conseguem entrar num estado de criptobiose e resistir ao vácuo, radiação extrema e temperaturas absurdas."
  },
  {
    "id": "SCI-005",
    "disciplina": "Ciência",
    "pergunta": "Qual destes metais pode derreter na palma da tua mão?",
    "opcaoA": "Ferro",
    "opcaoB": "Alumínio",
    "opcaoC": "Gálio",
    "opcaoD": "Titânio",
    "respostaCorreta": "C) Gálio",
    "curiosidade": "O gálio derrete por volta dos 30 °C. Basta segurá-lo alguns minutos para começar a transformar-se em líquido."
  },
  {
    "id": "SCI-006",
    "disciplina": "Ciência",
    "pergunta": "Qual destes órgãos consegue regenerar grande parte do seu tecido?",
    "opcaoA": "Coração",
    "opcaoB": "Pulmão",
    "opcaoC": "Fígado",
    "opcaoD": "Rim",
    "respostaCorreta": "C) Fígado",
    "curiosidade": "O fígado é um dos poucos órgãos humanos com uma extraordinária capacidade de regeneração, razão pela qual é possível fazer transplantes parciais."
  },
  {
    "id": "SCI-007",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem três corações?",
    "opcaoA": "Lula-gigante",
    "opcaoB": "Polvo",
    "opcaoC": "Tubarão",
    "opcaoD": "Baleia",
    "respostaCorreta": "B) Polvo",
    "curiosidade": "Dois corações enviam sangue para as guelras e um distribui sangue pelo resto do corpo."
  },
  {
    "id": "SCI-008",
    "disciplina": "Ciência",
    "pergunta": "Qual destes líquidos quentes congela, em determinadas condições, mais depressa do que um líquido frio?",
    "opcaoA": "Leite",
    "opcaoB": "Água",
    "opcaoC": "Azeite",
    "opcaoD": "Vinagre",
    "respostaCorreta": "B) Água",
    "curiosidade": "É o chamado Efeito Mpemba. Ainda hoje existem debates sobre os mecanismos exatos, mas o fenómeno já foi observado experimentalmente em determinadas condições."
  },
  {
    "id": "SCI-009",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dormir de olhos abertos?",
    "opcaoA": "Cavalo",
    "opcaoB": "Panda",
    "opcaoC": "Tigre",
    "opcaoD": "Canguru",
    "respostaCorreta": "A) Cavalo",
    "curiosidade": "Os cavalos conseguem descansar de pé graças a um sistema de bloqueio das pernas. Além disso, podem permanecer vigilantes durante parte do descanso."
  },
  {
    "id": "SCI-010",
    "disciplina": "Ciência",
    "pergunta": "Qual destes fenómenos acontece mesmo?",
    "opcaoA": "Chove peixe.",
    "opcaoB": "Há nuvens em forma de donut fixas sobre o Pólo Sul.",
    "opcaoC": "Existem vulcões que expelem granizo em vez de lava.",
    "opcaoD": "Há desertos onde a areia muda de cor todos os dias.",
    "respostaCorreta": "A) Chove peixe.",
    "curiosidade": "Sim! Já foram registadas \"chuvas\" de peixes associadas a tornados que erguem cardumes de lagos/rios e os deixam cair longe. (Nota: existem mesmo correntes densas tipo \"rios\" no fundo do mar e lagos cor-de-rosa por microrganismos — factos reais que podem voltar como perguntas à parte.)"
  },
  {
    "id": "SCI-011",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue mudar de sexo ao longo da vida?",
    "opcaoA": "Cavalo",
    "opcaoB": "Peixe-palhaço",
    "opcaoC": "Lobo",
    "opcaoD": "Águia",
    "respostaCorreta": "B) Peixe-palhaço",
    "curiosidade": "Nos grupos de peixes-palhaço, se a fêmea dominante morrer, o macho dominante pode mudar de sexo e assumir o seu lugar."
  },
  {
    "id": "SCI-012",
    "disciplina": "Ciência",
    "pergunta": "Qual destes órgãos não sente dor?",
    "opcaoA": "Fígado",
    "opcaoB": "Cérebro",
    "opcaoC": "Pulmão",
    "opcaoD": "Estômago",
    "respostaCorreta": "B) Cérebro",
    "curiosidade": "O cérebro não possui recetores de dor. É por isso que certas cirurgias cerebrais podem ser realizadas com o paciente acordado."
  },
  {
    "id": "SCI-013",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "No espaço ninguém consegue arrotar normalmente.",
    "opcaoB": "No espaço o cabelo deixa de crescer.",
    "opcaoC": "No espaço deixa-se de pestanejar.",
    "opcaoD": "No espaço perde-se o sentido do olfato.",
    "respostaCorreta": "A) No espaço ninguém consegue arrotar normalmente.",
    "curiosidade": "Sem gravidade, os gases e os líquidos no estômago não se separam da mesma forma, tornando o arroto... uma experiência completamente diferente."
  },
  {
    "id": "SCI-014",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dar um murro para atordoar a presa?",
    "opcaoA": "Lagosta",
    "opcaoB": "Camarão-pistola",
    "opcaoC": "Camarão-louva-a-deus",
    "opcaoD": "Caranguejo",
    "respostaCorreta": "C) Camarão-louva-a-deus",
    "curiosidade": "O camarão-louva-a-deus desfere golpes tão rápidos que cria pequenas bolhas de cavitação. O impacto é suficiente para partir conchas e até partir vidro fino de aquários."
  },
  {
    "id": "SCI-015",
    "disciplina": "Ciência",
    "pergunta": "Qual destes alimentos praticamente nunca se estraga?",
    "opcaoA": "Arroz",
    "opcaoB": "Mel",
    "opcaoC": "Sal",
    "opcaoD": "Açúcar",
    "respostaCorreta": "B) Mel",
    "curiosidade": "Já foi encontrado mel em túmulos do Antigo Egito com milhares de anos que continuava próprio para consumo, desde que estivesse bem preservado."
  },
  {
    "id": "SCI-016",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dormir com metade do cérebro de cada vez?",
    "opcaoA": "Golfinho",
    "opcaoB": "Gorila",
    "opcaoC": "Tigre",
    "opcaoD": "Canguru",
    "respostaCorreta": "A) Golfinho",
    "curiosidade": "Os golfinhos deixam apenas um hemisfério cerebral a dormir, permitindo-lhes continuar a respirar e vigiar predadores."
  },
  {
    "id": "SCI-017",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Os bebés nascem com mais ossos do que um adulto.",
    "opcaoB": "Os adultos têm mais dentes que os bebés.",
    "opcaoC": "O coração para durante um espirro.",
    "opcaoD": "O cabelo continua a crescer depois da morte.",
    "respostaCorreta": "A) Os bebés nascem com mais ossos do que um adulto.",
    "curiosidade": "Os bebés têm cerca de 270 ossos. À medida que crescem, muitos fundem-se, ficando um adulto com cerca de 206."
  },
  {
    "id": "SCI-018",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue sobreviver vários meses sem comer?",
    "opcaoA": "Leão",
    "opcaoB": "Pinguim-imperador",
    "opcaoC": "Cavalo",
    "opcaoD": "Lobo",
    "respostaCorreta": "B) Pinguim-imperador",
    "curiosidade": "Durante a incubação dos ovos, os machos podem passar mais de dois meses sem comer enquanto enfrentam o inverno antártico."
  },
  {
    "id": "SCI-019",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Existem mais árvores na Terra do que estrelas na Via Láctea.",
    "opcaoB": "Existem mais vulcões em Marte do que árvores na Terra.",
    "opcaoC": "Existem mais desertos em África do que rios no mundo.",
    "opcaoD": "Existem mais luas na Terra do que oceanos.",
    "respostaCorreta": "A) Existem mais árvores na Terra do que estrelas na Via Láctea.",
    "curiosidade": "As estimativas apontam para cerca de 3 biliões (trillion em inglês) de árvores no planeta, enquanto a Via Láctea deverá ter entre 100 e 400 mil milhões de estrelas."
  },
  {
    "id": "SCI-020",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Os tubarões são mais antigos do que as árvores.",
    "opcaoB": "As abelhas existiam antes dos dinossauros.",
    "opcaoC": "Os humanos coexistiram com os tiranossauros.",
    "opcaoD": "Os cavalos apareceram antes dos peixes.",
    "respostaCorreta": "A) Os tubarões são mais antigos do que as árvores.",
    "curiosidade": "Os primeiros tubarões surgiram há mais de 400 milhões de anos. As primeiras árvores apareceram dezenas de milhões de anos depois."
  },
  {
    "id": "SCI-021",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem um pénis em forma de saca-rolhas?",
    "opcaoA": "Pato",
    "opcaoB": "Cisne",
    "opcaoC": "Peru",
    "opcaoD": "Ganso",
    "respostaCorreta": "A) Pato",
    "curiosidade": "Algumas espécies de patos desenvolveram órgãos reprodutores em forma de espiral. Curiosamente, as fêmeas desenvolveram o trato reprodutor com curvas em sentido oposto, num verdadeiro exemplo de \"corrida evolutiva\" entre os sexos."
  },
  {
    "id": "SCI-022",
    "disciplina": "Ciência",
    "pergunta": "Qual destas partes do corpo produz a maior parte da cera dos ouvidos?",
    "opcaoA": "Glândulas do canal auditivo",
    "opcaoB": "Tímpano",
    "opcaoC": "Lóbulo",
    "opcaoD": "Cartilagem da orelha",
    "respostaCorreta": "A) Glândulas do canal auditivo",
    "curiosidade": "A cera protege o ouvido contra poeiras, fungos, bactérias e pequenos insetos. Sim... insetos."
  },
  {
    "id": "SCI-023",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais morre pouco tempo depois de acasalar?",
    "opcaoA": "Polvo",
    "opcaoB": "Cavalo",
    "opcaoC": "Leão",
    "opcaoD": "Coruja",
    "respostaCorreta": "A) Polvo",
    "curiosidade": "Nos polvos, os machos morrem pouco depois do acasalamento e muitas fêmeas morrem após protegerem os ovos durante semanas ou meses sem comer."
  },
  {
    "id": "SCI-024",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Os humanos brilham no escuro.",
    "opcaoB": "O sangue é azul dentro do corpo.",
    "opcaoC": "O coração fica do lado direito.",
    "opcaoD": "Os ossos são ocos.",
    "respostaCorreta": "A) Os humanos brilham no escuro.",
    "curiosidade": "O corpo humano emite uma luz extremamente fraca devido a processos metabólicos. É milhões de vezes mais fraca do que aquilo que o olho humano consegue ver."
  },
  {
    "id": "SCI-025",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue mudar de sexo várias vezes ao longo da vida?",
    "opcaoA": "Peixe-limpador-azul",
    "opcaoB": "Golfinho",
    "opcaoC": "Lobo",
    "opcaoD": "Águia",
    "respostaCorreta": "A) Peixe-limpador-azul",
    "curiosidade": "Algumas espécies de peixes podem alternar entre macho e fêmea mais do que uma vez, dependendo da estrutura social do grupo."
  },
  {
    "id": "SCI-026",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O estômago produz ácido suficientemente forte para dissolver uma lâmina de barbear.",
    "opcaoB": "O fígado nunca cresce.",
    "opcaoC": "O cérebro pesa menos que um limão.",
    "opcaoD": "Os pulmões são músculos.",
    "respostaCorreta": "A) O estômago produz ácido suficientemente forte para dissolver uma lâmina de barbear.",
    "curiosidade": "O ácido do estômago é extremamente forte. Felizmente, o revestimento do estômago renova-se constantemente para evitar que ele se \"digira\" a si próprio."
  },
  {
    "id": "SCI-027",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais pratica sexo por prazer, e não apenas para reprodução?",
    "opcaoA": "Golfinho",
    "opcaoB": "Girafa",
    "opcaoC": "Rinoceronte",
    "opcaoD": "Zebra",
    "respostaCorreta": "A) Golfinho",
    "curiosidade": "Os golfinhos são uma das poucas espécies conhecidas que têm comportamentos sexuais ligados também ao prazer, às relações sociais e à brincadeira."
  },
  {
    "id": "SCI-028",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Todos os seres humanos têm pequenas quantidades de ouro no corpo.",
    "opcaoB": "Todos os seres humanos têm diamantes microscópicos no sangue.",
    "opcaoC": "Todos os seres humanos têm prata nos ossos.",
    "opcaoD": "Todos os seres humanos têm mercúrio no coração.",
    "respostaCorreta": "A) Todos os seres humanos têm pequenas quantidades de ouro no corpo.",
    "curiosidade": "Existem vestígios de ouro distribuídos pelo organismo, mas em quantidades tão pequenas que seriam precisas dezenas de milhares de pessoas para obter apenas alguns gramas."
  },
  {
    "id": "SCI-029",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem uma fêmea cujo órgão sexual pode parecer um pénis?",
    "opcaoA": "Hiena-malhada",
    "opcaoB": "Leoa",
    "opcaoC": "Zebra",
    "opcaoD": "Loba",
    "respostaCorreta": "A) Hiena-malhada",
    "curiosidade": "As hienas-malhadas fêmeas têm um clítoris extremamente desenvolvido, uma característica rara entre os mamíferos e muito estudada pelos biólogos."
  },
  {
    "id": "SCI-030",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O sémen humano contém várias proteínas diferentes.",
    "opcaoB": "O sémen é composto apenas por espermatozoides.",
    "opcaoC": "O sémen é produzido apenas nos testículos.",
    "opcaoD": "O sémen humano não contém vitaminas.",
    "respostaCorreta": "A) O sémen humano contém várias proteínas diferentes.",
    "curiosidade": "O sémen é um fluido complexo produzido por várias glândulas do aparelho reprodutor masculino. Contém mais de 200 proteínas diferentes, além de açúcares, minerais e enzimas."
  },
  {
    "id": "EST-001",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais provoca mais mortes humanas por ano?",
    "opcaoA": "Tubarão",
    "opcaoB": "Leão",
    "opcaoC": "Mosquito",
    "opcaoD": "Lobo",
    "respostaCorreta": "C) Mosquito",
    "curiosidade": "Os mosquitos transmitem doenças como a malária e a dengue, sendo responsáveis por centenas de milhares de mortes todos os anos."
  },
  {
    "id": "EST-002",
    "disciplina": "Estatística",
    "pergunta": "Qual destas passwords esteve durante anos entre as mais usadas no mundo?",
    "opcaoA": "ilovepizza",
    "opcaoB": "password",
    "opcaoC": "superhomem",
    "opcaoD": "portugal123",
    "respostaCorreta": "B) password",
    "curiosidade": "Todos os anos aparecem milhões de contas protegidas com \"password\", \"123456\" ou \"qwerty\". Sim... ainda em 2026."
  },
  {
    "id": "EST-003",
    "disciplina": "Estatística",
    "pergunta": "Qual destes músculos trabalha mais vezes ao longo de um dia normal?",
    "opcaoA": "Bíceps",
    "opcaoB": "Coração",
    "opcaoC": "Gémeos",
    "opcaoD": "Pescoço",
    "respostaCorreta": "B) Coração",
    "curiosidade": "O coração bate cerca de 100 mil vezes por dia, sem pausas."
  },
  {
    "id": "EST-004",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países consome, em média, mais café por habitante?",
    "opcaoA": "Itália",
    "opcaoB": "Portugal",
    "opcaoC": "Finlândia",
    "opcaoD": "Brasil",
    "respostaCorreta": "C) Finlândia",
    "curiosidade": "A Finlândia lidera regularmente os rankings mundiais de consumo de café por pessoa."
  },
  {
    "id": "EST-005",
    "disciplina": "Estatística",
    "pergunta": "Qual destes emojis é habitualmente o mais utilizado no mundo?",
    "opcaoA": "❤️",
    "opcaoB": "😂",
    "opcaoC": "👍",
    "opcaoD": "😎",
    "respostaCorreta": "B) 😂",
    "curiosidade": "O 😂 liderou durante anos os rankings globais de utilização, embora a ordem varie ligeiramente entre plataformas e anos."
  },
  {
    "id": "EST-006",
    "disciplina": "Estatística",
    "pergunta": "Qual destes líquidos é o mais consumido no mundo, a seguir à água?",
    "opcaoA": "Café",
    "opcaoB": "Refrigerantes",
    "opcaoC": "Chá",
    "opcaoD": "Leite",
    "respostaCorreta": "C) Chá",
    "curiosidade": "O chá é consumido diariamente por milhares de milhões de pessoas em praticamente todos os continentes."
  },
  {
    "id": "EST-007",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais dorme mais horas por dia, em média?",
    "opcaoA": "Coala",
    "opcaoB": "Gato",
    "opcaoC": "Panda",
    "opcaoD": "Preguiça",
    "respostaCorreta": "A) Coala",
    "curiosidade": "Os coalas podem dormir entre 18 e 22 horas por dia devido à dieta pobre em energia."
  },
  {
    "id": "EST-008",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais fusos horários?",
    "opcaoA": "Rússia",
    "opcaoB": "Estados Unidos",
    "opcaoC": "França",
    "opcaoD": "Canadá",
    "respostaCorreta": "C) França",
    "curiosidade": "Graças aos seus territórios ultramarinos, a França é frequentemente considerada o país com mais fusos horários."
  },
  {
    "id": "EST-009",
    "disciplina": "Estatística",
    "pergunta": "Qual destas redes sociais ultrapassou primeiro mil milhões de utilizadores?",
    "opcaoA": "TikTok",
    "opcaoB": "Instagram",
    "opcaoC": "Facebook",
    "opcaoD": "Snapchat",
    "respostaCorreta": "C) Facebook",
    "curiosidade": "O Facebook foi a primeira grande rede social a atingir esse marco histórico."
  },
  {
    "id": "EST-010",
    "disciplina": "Estatística",
    "pergunta": "Qual destes alimentos é o mais roubado em supermercados de todo o mundo?",
    "opcaoA": "Chocolate",
    "opcaoB": "Queijo",
    "opcaoC": "Café",
    "opcaoD": "Atum",
    "respostaCorreta": "B) Queijo",
    "curiosidade": "Parece brincadeira, mas vários estudos sobre perdas no retalho apontam o queijo como um dos produtos alimentares mais furtados no mundo, devido ao seu valor e facilidade de revenda."
  },
  {
    "id": "EST-011",
    "disciplina": "Estatística",
    "pergunta": "Qual destes desportos tem mais praticantes no mundo?",
    "opcaoA": "Ténis",
    "opcaoB": "Futebol",
    "opcaoC": "Basquetebol",
    "opcaoD": "Natação",
    "respostaCorreta": "B) Futebol",
    "curiosidade": "Estima-se que mais de 3 mil milhões de pessoas acompanhem ou pratiquem futebol regularmente."
  },
  {
    "id": "EST-012",
    "disciplina": "Estatística",
    "pergunta": "Qual destes vídeos foi o primeiro a ultrapassar os 10 mil milhões de visualizações no YouTube?",
    "opcaoA": "Gangnam Style",
    "opcaoB": "Baby Shark",
    "opcaoC": "Despacito",
    "opcaoD": "Shape of You",
    "respostaCorreta": "B) Baby Shark",
    "curiosidade": "\"Baby Shark\" tornou-se o vídeo mais visto da história do YouTube e foi o primeiro a ultrapassar a marca dos 10 mil milhões de visualizações."
  },
  {
    "id": "EST-013",
    "disciplina": "Estatística",
    "pergunta": "Qual destes mamíferos passa mais tempo a dormir por dia?",
    "opcaoA": "Morcego-castanho",
    "opcaoB": "Coala",
    "opcaoC": "Leão",
    "opcaoD": "Gato",
    "respostaCorreta": "A) Morcego-castanho",
    "curiosidade": "Algumas espécies de morcegos chegam a dormir cerca de 20 horas por dia."
  },
  {
    "id": "EST-014",
    "disciplina": "Estatística",
    "pergunta": "Qual destes alimentos é consumido em maior quantidade no mundo?",
    "opcaoA": "Arroz",
    "opcaoB": "Batata",
    "opcaoC": "Massa",
    "opcaoD": "Pão",
    "respostaCorreta": "A) Arroz",
    "curiosidade": "O arroz é a base alimentar de milhares de milhões de pessoas, sobretudo na Ásia."
  },
  {
    "id": "EST-015",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem a maior população?",
    "opcaoA": "Estados Unidos",
    "opcaoB": "Índia",
    "opcaoC": "Rússia",
    "opcaoD": "Brasil",
    "respostaCorreta": "B) Índia",
    "curiosidade": "A Índia ultrapassou a China como o país mais populoso do mundo."
  },
  {
    "id": "EST-016",
    "disciplina": "Estatística",
    "pergunta": "Qual destes objetos é mais perdido em hotéis?",
    "opcaoA": "Carregadores de telemóvel",
    "opcaoB": "Sapatos",
    "opcaoC": "Casacos",
    "opcaoD": "Carteiras",
    "respostaCorreta": "A) Carregadores de telemóvel",
    "curiosidade": "Os carregadores estão entre os objetos mais esquecidos em hotéis, precisamente porque costumam ficar ligados às tomadas."
  },
  {
    "id": "EST-017",
    "disciplina": "Estatística",
    "pergunta": "Qual destes músculos é considerado o mais forte do corpo humano em termos de força exercida?",
    "opcaoA": "Bíceps",
    "opcaoB": "Língua",
    "opcaoC": "Masséter (mandíbula)",
    "opcaoD": "Gémeos",
    "respostaCorreta": "C) Masséter (mandíbula)",
    "curiosidade": "O masséter, usado para mastigar, consegue exercer uma enorme força de mordida."
  },
  {
    "id": "EST-018",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países produz mais queijo?",
    "opcaoA": "França",
    "opcaoB": "Itália",
    "opcaoC": "Estados Unidos",
    "opcaoD": "Suíça",
    "respostaCorreta": "C) Estados Unidos",
    "curiosidade": "Apesar da fama europeia, os Estados Unidos lideram há anos a produção mundial de queijo."
  },
  {
    "id": "EST-019",
    "disciplina": "Estatística",
    "pergunta": "Qual destes domínios é o mais visitado no mundo?",
    "opcaoA": "wikipedia.org",
    "opcaoB": "youtube.com",
    "opcaoC": "google.com",
    "opcaoD": "amazon.com",
    "respostaCorreta": "C) google.com",
    "curiosidade": "O Google continua a liderar os rankings globais de tráfego na internet."
  },
  {
    "id": "EST-020",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais mata mais seres humanos diretamente?",
    "opcaoA": "Hipopótamo",
    "opcaoB": "Crocodilo",
    "opcaoC": "Cobra",
    "opcaoD": "Tubarão",
    "respostaCorreta": "C) Cobra",
    "curiosidade": "As mordeduras de cobras venenosas causam dezenas de milhares de mortes por ano. Os tubarões, apesar da fama, provocam muito menos vítimas."
  },
  {
    "id": "EST-021",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais ilhas?",
    "opcaoA": "Indonésia",
    "opcaoB": "Filipinas",
    "opcaoC": "Suécia",
    "opcaoD": "Japão",
    "respostaCorreta": "C) Suécia",
    "curiosidade": "A Suécia tem cerca de 267 mil ilhas, embora apenas uma pequena parte seja habitada."
  },
  {
    "id": "EST-022",
    "disciplina": "Estatística",
    "pergunta": "Qual destas empresas vende mais consolas de videojogos?",
    "opcaoA": "Sega",
    "opcaoB": "Microsoft",
    "opcaoC": "Nintendo",
    "opcaoD": "Sony",
    "respostaCorreta": "D) Sony",
    "curiosidade": "Com a família PlayStation, a Sony tornou-se a fabricante de consolas domésticas mais bem-sucedida da história."
  },
  {
    "id": "EST-023",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países produz mais vinho?",
    "opcaoA": "França",
    "opcaoB": "Itália",
    "opcaoC": "Espanha",
    "opcaoD": "Portugal",
    "respostaCorreta": "B) Itália",
    "curiosidade": "A liderança alterna entre Itália e França consoante o ano, mas Itália ocupa frequentemente o primeiro lugar na produção mundial."
  },
  {
    "id": "EST-024",
    "disciplina": "Estatística",
    "pergunta": "Qual destes produtos é mais roubado em hotéis?",
    "opcaoA": "Toalhas",
    "opcaoB": "Copos",
    "opcaoC": "Almofadas",
    "opcaoD": "Comandos da televisão",
    "respostaCorreta": "A) Toalhas",
    "curiosidade": "As toalhas continuam entre os objetos mais levados pelos hóspedes. Sim... há quem ache que estão incluídas no preço."
  },
  {
    "id": "EST-025",
    "disciplina": "Estatística",
    "pergunta": "Qual destas aplicações é descarregada mais vezes no mundo?",
    "opcaoA": "TikTok",
    "opcaoB": "WhatsApp",
    "opcaoC": "Discord",
    "opcaoD": "Spotify",
    "respostaCorreta": "B) WhatsApp",
    "curiosidade": "O WhatsApp mantém-se entre as aplicações mais descarregadas e utilizadas globalmente, graças à enorme base de utilizadores."
  },
  {
    "id": "EST-026",
    "disciplina": "Estatística",
    "pergunta": "Qual destas coisas acontece mais vezes durante um dia normal?",
    "opcaoA": "Pestanejar",
    "opcaoB": "Engolir",
    "opcaoC": "Bocejar",
    "opcaoD": "Espirrar",
    "respostaCorreta": "A) Pestanejar",
    "curiosidade": "Uma pessoa pode pestanejar entre 15 e 20 mil vezes por dia, quase sem dar por isso."
  },
  {
    "id": "EST-027",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais vive, em média, mais tempo?",
    "opcaoA": "Elefante",
    "opcaoB": "Tartaruga-gigante",
    "opcaoC": "Baleia-azul",
    "opcaoD": "Crocodilo",
    "respostaCorreta": "B) Tartaruga-gigante",
    "curiosidade": "Algumas tartarugas-gigantes ultrapassam os 180 anos, tornando-se dos vertebrados mais longevos conhecidos."
  },
  {
    "id": "EST-028",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países consome mais chocolate por pessoa?",
    "opcaoA": "Bélgica",
    "opcaoB": "Alemanha",
    "opcaoC": "Suíça",
    "opcaoD": "Reino Unido",
    "respostaCorreta": "C) Suíça",
    "curiosidade": "A Suíça está regularmente entre os países com maior consumo de chocolate por habitante."
  },
  {
    "id": "EST-029",
    "disciplina": "Estatística",
    "pergunta": "Qual destes idiomas tem mais falantes nativos?",
    "opcaoA": "Inglês",
    "opcaoB": "Espanhol",
    "opcaoC": "Hindi",
    "opcaoD": "Mandarim",
    "respostaCorreta": "D) Mandarim",
    "curiosidade": "O mandarim é a língua com mais falantes nativos do planeta, muito à frente do inglês."
  },
  {
    "id": "EST-030",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais pirâmides?",
    "opcaoA": "Egito",
    "opcaoB": "México",
    "opcaoC": "Sudão",
    "opcaoD": "Peru",
    "respostaCorreta": "C) Sudão",
    "curiosidade": "O Sudão possui mais de 200 pirâmides, ultrapassando largamente o Egito. Foram construídas pelo antigo Reino de Cuxe."
  },
  {
    "id": "POP-001",
    "disciplina": "Cultura & Caos",
    "pergunta": "Como se chamava originalmente o Mario quando apareceu pela primeira vez?",
    "opcaoA": "Luigi",
    "opcaoB": "Jumpman",
    "opcaoC": "Plumber Joe",
    "opcaoD": "Mr. Nintendo",
    "respostaCorreta": "B) Jumpman",
    "curiosidade": "Na sua estreia em Donkey Kong (1981), Mario era apenas conhecido por Jumpman. O nome \"Mario\" surgiu mais tarde, inspirado num senhorio dos escritórios da Nintendo of America."
  },
  {
    "id": "POP-002",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes atores recusou interpretar Neo em The Matrix?",
    "opcaoA": "Brad Pitt",
    "opcaoB": "Will Smith",
    "opcaoC": "Keanu Reeves",
    "opcaoD": "Tom Cruise",
    "respostaCorreta": "B) Will Smith",
    "curiosidade": "Will Smith recusou o papel porque não percebeu bem o argumento. Acabou por fazer Wild Wild West... uma decisão que ele próprio já admitiu arrepender-se de ter tomado."
  },
  {
    "id": "POP-003",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes jogos foi proibido em vários países devido ao nível de violência?",
    "opcaoA": "The Sims",
    "opcaoB": "Manhunt 2",
    "opcaoC": "Minecraft",
    "opcaoD": "Rocket League",
    "respostaCorreta": "B) Manhunt 2",
    "curiosidade": "Manhunt 2 foi proibido ou censurado em vários países, tornando-se um dos videojogos mais controversos da sua época."
  },
  {
    "id": "POP-004",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes memes nasceu de uma fotografia verdadeira?",
    "opcaoA": "Disaster Girl",
    "opcaoB": "Trollface",
    "opcaoC": "Rage Guy",
    "opcaoD": "Wojak",
    "respostaCorreta": "A) Disaster Girl",
    "curiosidade": "A fotografia da \"Disaster Girl\" mostra uma menina real a sorrir enquanto uma casa arde ao fundo durante um treino controlado dos bombeiros."
  },
  {
    "id": "POP-005",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes filmes ganhou 11 Óscares?",
    "opcaoA": "Titanic",
    "opcaoB": "Avatar",
    "opcaoC": "Joker",
    "opcaoD": "Barbie",
    "respostaCorreta": "A) Titanic",
    "curiosidade": "Titanic igualou o recorde de 11 Óscares, feito que também pertence a Ben-Hur e O Senhor dos Anéis: O Regresso do Rei."
  },
  {
    "id": "POP-006",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas personagens da Nintendo nem sequer foi criada para ser protagonista?",
    "opcaoA": "Link",
    "opcaoB": "Kirby",
    "opcaoC": "Mario",
    "opcaoD": "Samus",
    "respostaCorreta": "C) Mario",
    "curiosidade": "Mario nasceu apenas como personagem principal de Donkey Kong. A Nintendo nunca imaginou que se tornaria a cara da empresa durante décadas."
  },
  {
    "id": "POP-007",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas séries terminou com uma petição online para refazer a última temporada?",
    "opcaoA": "Breaking Bad",
    "opcaoB": "Game of Thrones",
    "opcaoC": "Friends",
    "opcaoD": "The Office",
    "respostaCorreta": "B) Game of Thrones",
    "curiosidade": "Mais de um milhão de pessoas assinaram uma petição a pedir que a oitava temporada fosse refeita."
  },
  {
    "id": "POP-008",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas músicas é atualmente uma das mais reproduzidas de sempre no Spotify?",
    "opcaoA": "Bohemian Rhapsody",
    "opcaoB": "Blinding Lights",
    "opcaoC": "Gangnam Style",
    "opcaoD": "Wonderwall",
    "respostaCorreta": "B) Blinding Lights",
    "curiosidade": "A música de The Weeknd tornou-se a faixa mais reproduzida da história da plataforma."
  },
  {
    "id": "POP-009",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas plataformas nasceu originalmente como um site de encontros?",
    "opcaoA": "Facebook",
    "opcaoB": "YouTube",
    "opcaoC": "Reddit",
    "opcaoD": "Discord",
    "respostaCorreta": "B) YouTube",
    "curiosidade": "Os fundadores imaginaram o YouTube como um site onde as pessoas podiam carregar vídeos para se apresentarem a potenciais parceiros. A ideia não pegou... e decidiram abrir a plataforma a todo o tipo de vídeos."
  },
  {
    "id": "POP-010",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas personagens de videojogos é canonicamente mais velha?",
    "opcaoA": "Sonic",
    "opcaoB": "Master Chief",
    "opcaoC": "Pac-Man",
    "opcaoD": "Crash Bandicoot",
    "respostaCorreta": "C) Pac-Man",
    "curiosidade": "Pac-Man nasceu em 1980, tornando-se uma das personagens mais antigas e icónicas da história dos videojogos."
  },
  {
    "id": "POP-011",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase?",
    "opcaoA": "José Mourinho",
    "opcaoB": "Jorge Jesus",
    "opcaoC": "Toni",
    "opcaoD": "Fernando Santos",
    "respostaCorreta": "B) Jorge Jesus",
    "curiosidade": "Jorge Jesus tornou-se uma verdadeira fábrica de frases memoráveis. Muitas acabaram por entrar na cultura popular portuguesa."
  },
  {
    "id": "POP-012",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes programas continua há mais anos consecutivos no ar?",
    "opcaoA": "Praça da Alegria",
    "opcaoB": "Preço Certo",
    "opcaoC": "Você na TV",
    "opcaoD": "Big Show SIC",
    "respostaCorreta": "B) Preço Certo",
    "curiosidade": "O Preço Certo estreou em Portugal em 2002 com Fernando Mendes e continua a ser um dos programas mais vistos da televisão portuguesa."
  },
  {
    "id": "POP-013",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas frases nasceu mesmo de um momento televisivo?",
    "opcaoA": "\"Ai Jesus!\"",
    "opcaoB": "\"É lidar, irmoum.\"",
    "opcaoC": "\"É uma maravilha.\"",
    "opcaoD": "\"Tá bonito, tá.\"",
    "respostaCorreta": "C) \"É uma maravilha.\"",
    "curiosidade": "Fernando Mendes transformou várias expressões espontâneas em autênticos memes nacionais."
  },
  {
    "id": "POP-014",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes memes nasceu de uma fotografia tirada num treino dos bombeiros?",
    "opcaoA": "Hide the Pain Harold",
    "opcaoB": "Disaster Girl",
    "opcaoC": "Success Kid",
    "opcaoD": "Bad Luck Brian",
    "respostaCorreta": "B) Disaster Girl",
    "curiosidade": "A casa estava a ser queimada de forma controlada. A fotografia da pequena Zoe tornou-se um dos memes mais famosos da internet."
  },
  {
    "id": "POP-015",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem ficou conhecido por dizer inúmeras vezes a palavra \"treta\" em conferências de imprensa?",
    "opcaoA": "José Peseiro",
    "opcaoB": "Jorge Jesus",
    "opcaoC": "Octávio Machado",
    "opcaoD": "José Mourinho",
    "respostaCorreta": "D) José Mourinho",
    "curiosidade": "Mourinho tornou famosas muitas conferências de imprensa pela forma direta e pelas respostas afiadas aos jornalistas."
  },
  {
    "id": "POP-016",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes sons foi gravado usando um porco-da-índia?",
    "opcaoA": "Sonic",
    "opcaoB": "Pokémon",
    "opcaoC": "Donkey Kong",
    "opcaoD": "Yoshi",
    "respostaCorreta": "D) Yoshi",
    "curiosidade": "A voz clássica do Yoshi foi criada manipulando gravações feitas pelo compositor Kazumi Totaka."
  },
  {
    "id": "POP-017",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes apresentadores apresenta o Preço Certo desde o primeiro episódio português?",
    "opcaoA": "João Baião",
    "opcaoB": "Fernando Mendes",
    "opcaoC": "Herman José",
    "opcaoD": "José Figueiras",
    "respostaCorreta": "B) Fernando Mendes",
    "curiosidade": "É uma das carreiras mais longas da televisão portuguesa no mesmo formato."
  },
  {
    "id": "POP-018",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas plataformas tornou famosa a expressão \"Rickroll\"?",
    "opcaoA": "Facebook",
    "opcaoB": "YouTube",
    "opcaoC": "Twitch",
    "opcaoD": "Reddit",
    "respostaCorreta": "B) YouTube",
    "curiosidade": "O Rickroll espalhou-se através do YouTube, onde milhões de pessoas eram enganadas para abrir o videoclip de Never Gonna Give You Up."
  },
  {
    "id": "POP-019",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase?",
    "opcaoA": "Toni",
    "opcaoB": "Jorge Jesus",
    "opcaoC": "Mourinho",
    "opcaoD": "Manuel Machado",
    "respostaCorreta": "B) Jorge Jesus",
    "curiosidade": "As conferências de imprensa de Jorge Jesus continuam a alimentar páginas de memes anos depois de terem acontecido."
  },
  {
    "id": "POP-020",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas pessoas ficou conhecida em Portugal por gritar repetidamente...",
    "opcaoA": "Fernando Mendes",
    "opcaoB": "Batatinha",
    "opcaoC": "Emanuel",
    "opcaoD": "Toy",
    "respostaCorreta": "D) Toy",
    "curiosidade": "A expressão tornou-se inseparável dos concertos do Toy e acabou por entrar no vocabulário popular."
  },
  {
    "id": "POP-021",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase?",
    "opcaoA": "Jorge Jesus",
    "opcaoB": "Manuel Machado",
    "opcaoC": "João Pinto",
    "opcaoD": "É um meme da internet — nunca foi dita por nenhum treinador real.",
    "respostaCorreta": "D) É um meme da internet — nunca foi dita por nenhum treinador real.",
    "curiosidade": "Apesar de parecer uma frase saída de uma conferência de imprensa, esta nunca foi dita por nenhum destes treinadores. É um daqueles \"memes\" que a internet acabou por transformar em verdade."
  },
  {
    "id": "POP-022",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes programas portugueses usava realmente um famoso telefone vermelho?",
    "opcaoA": "Big Show SIC",
    "opcaoB": "Preço Certo",
    "opcaoC": "1 Contra Todos",
    "opcaoD": "Quem Quer Ser Milionário?",
    "respostaCorreta": "A) Big Show SIC",
    "curiosidade": "O telefone vermelho do Big Show SIC tornou-se um dos objetos mais icónicos da televisão portuguesa dos anos 90."
  },
  {
    "id": "POP-023",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas frases nasceu de uma publicidade e ficou famosa em Portugal?",
    "opcaoA": "\"Há mar e mar...\"",
    "opcaoB": "\"É só fazer as contas.\"",
    "opcaoC": "\"É um espetáculo!\"",
    "opcaoD": "\"Um bocadinho assim.\"",
    "respostaCorreta": "D) \"Um bocadinho assim.\"",
    "curiosidade": "A expressão entrou no vocabulário popular depois de uma campanha publicitária e ainda hoje é reconhecida por muita gente."
  },
  {
    "id": "POP-024",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes treinadores ficou particularmente conhecido pelas suas \"jesuadas\", trocando frequentemente palavras e expressões?",
    "opcaoA": "Fernando Santos",
    "opcaoB": "Jorge Jesus",
    "opcaoC": "Paulo Bento",
    "opcaoD": "Carlos Queiroz",
    "respostaCorreta": "B) Jorge Jesus",
    "curiosidade": "As conferências de Jorge Jesus deram origem a dezenas de páginas, vídeos e compilações de frases memoráveis."
  },
  {
    "id": "POP-025",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes youtubers portugueses começou por fazer vídeos de Minecraft?",
    "opcaoA": "RicFazeres",
    "opcaoB": "Wuant",
    "opcaoC": "Numeiro",
    "opcaoD": "Windoh",
    "respostaCorreta": "A) RicFazeres",
    "curiosidade": "O RicFazeres tornou-se um dos maiores criadores de conteúdo portugueses muito graças às suas séries de Minecraft."
  },
  {
    "id": "POP-026",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes apresentadores é conhecido como \"O Gordo\" em inúmeros memes da internet portuguesa?",
    "opcaoA": "Malato",
    "opcaoB": "Fernando Mendes",
    "opcaoC": "Goucha",
    "opcaoD": "Baião",
    "respostaCorreta": "B) Fernando Mendes",
    "curiosidade": "Fernando Mendes tornou-se uma das personalidades mais memeadas da televisão portuguesa, sempre com muito bom humor."
  },
  {
    "id": "POP-027",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes artistas ficou conhecido pela frase...",
    "opcaoA": "Quim Barreiros",
    "opcaoB": "Emanuel",
    "opcaoC": "Toy",
    "opcaoD": "Nel Monteiro",
    "respostaCorreta": "C) Toy",
    "curiosidade": "É praticamente impossível ouvir esta expressão sem pensar imediatamente num concerto do Toy."
  },
  {
    "id": "POP-028",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes memes nasceu mesmo em Portugal?",
    "opcaoA": "Batatinha à porrada",
    "opcaoB": "Doge",
    "opcaoC": "Trollface",
    "opcaoD": "Success Kid",
    "respostaCorreta": "A) Batatinha à porrada",
    "curiosidade": "Embora nunca tenha sido provado que a alegada \"luta\" aconteceu, o meme tornou-se uma das maiores lendas da televisão portuguesa."
  },
  {
    "id": "POP-029",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes concursos ficou famoso por oferecer... um automóvel em praticamente todos os programas?",
    "opcaoA": "A Roda da Sorte",
    "opcaoB": "Preço Certo",
    "opcaoC": "Chuva de Estrelas",
    "opcaoD": "Quem Quer Ser Milionário?",
    "respostaCorreta": "B) Preço Certo",
    "curiosidade": "O momento da revelação do automóvel tornou-se um clássico da televisão portuguesa."
  },
  {
    "id": "POP-030",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas expressões foi realmente dita por Jorge Jesus?",
    "opcaoA": "\"Não somos favoritos, somos favoritados.\"",
    "opcaoB": "\"O importante é marcar mais golos do que o adversário.\"",
    "opcaoC": "\"Em termos exibicionais estivemos muito bem exibidos.\"",
    "opcaoD": "\"O empate é uma vitória sem ganhar.\"",
    "respostaCorreta": "C) \"Em termos exibicionais estivemos muito bem exibidos.\"",
    "curiosidade": "Jorge Jesus deixou dezenas de expressões únicas ao longo da carreira. Algumas parecem inventadas... mas foram mesmo ditas."
  }
];
