// Dados carregados por api/universidade/admin.js — gerado a partir do documento auditado (200 perguntas)
export const questionsData = [
  {
    "id": "GEO-001",
    "disciplina": "Geografia",
    "pergunta": "Qual destes locais portugueses existe mesmo?",
    "opcaoA": "Jardim dos Bigodes Tristes",
    "opcaoB": "Jardim dos Tomates Secos",
    "opcaoC": "Jardim das Barbas Caídas",
    "opcaoD": "Jardim das Pichas Murchas",
    "respostaCorreta": "D) Jardim das Pichas Murchas",
    "curiosidade": "O Jardim das Pichas Murchas existe mesmo em Lisboa, na freguesia de São Vicente. O nome nasceu de uma brincadeira popular e acabou por ficar na toponímia local."
  },
  {
    "id": "GEO-002",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Monte do Saxofone",
    "opcaoB": "Aldeia da Sanfona",
    "opcaoC": "Venda da Gaita",
    "opcaoD": "Feira do Trombone",
    "respostaCorreta": "C) Venda da Gaita",
    "curiosidade": "Venda da Gaita é uma localidade real no concelho de Pedrógão Grande e aparece frequentemente nas listas dos nomes mais curiosos de Portugal."
  },
  {
    "id": "GEO-003",
    "disciplina": "Geografia",
    "pergunta": "Qual é o maior país do mundo em área?",
    "opcaoA": "Rússia",
    "opcaoB": "Estados Unidos",
    "opcaoC": "China",
    "opcaoD": "Canadá",
    "respostaCorreta": "A) Rússia",
    "curiosidade": "A Rússia ocupa cerca de 17 milhões de km² e atravessa 11 fusos horários."
  },
  {
    "id": "GEO-004",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem uma bandeira que não é retangular?",
    "opcaoA": "Butão",
    "opcaoB": "Sri Lanka",
    "opcaoC": "Nepal",
    "opcaoD": "Laos",
    "respostaCorreta": "C) Nepal",
    "curiosidade": "A bandeira do Nepal é formada por dois triângulos sobrepostos e é única entre os países soberanos."
  },
  {
    "id": "GEO-005",
    "disciplina": "Geografia",
    "pergunta": "Qual destas cidades é capital da Austrália?",
    "opcaoA": "Melbourne",
    "opcaoB": "Canberra",
    "opcaoC": "Perth",
    "opcaoD": "Sydney",
    "respostaCorreta": "B) Canberra",
    "curiosidade": "Canberra foi construída de propósito para evitar rivalidades entre Sydney e Melbourne."
  },
  {
    "id": "GEO-006",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países não tem saída para o mar?",
    "opcaoA": "Peru",
    "opcaoB": "Chile",
    "opcaoC": "Equador",
    "opcaoD": "Bolívia",
    "respostaCorreta": "D) Bolívia",
    "curiosidade": "A Bolívia perdeu a sua costa para o Chile na Guerra do Pacífico, no século XIX."
  },
  {
    "id": "GEO-007",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Ovelhas do Norte",
    "opcaoB": "Carneiros Felizes",
    "opcaoC": "Cabrões",
    "opcaoD": "Burros Unidos",
    "respostaCorreta": "C) Cabrões",
    "curiosidade": "Cabrões é uma localidade real do concelho de Santo Tirso e costuma aparecer em listas de topónimos insólitos portugueses."
  },
  {
    "id": "GEO-008",
    "disciplina": "Geografia",
    "pergunta": "Qual destas ilhas pertence a Portugal?",
    "opcaoA": "El Hierro",
    "opcaoB": "Tenerife",
    "opcaoC": "La Gomera",
    "opcaoD": "Porto Santo",
    "respostaCorreta": "D) Porto Santo",
    "curiosidade": "Porto Santo faz parte do arquipélago da Madeira e é conhecida pela sua praia de areia dourada com cerca de 9 km."
  },
  {
    "id": "GEO-010",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é atravessado por mais fusos horários?",
    "opcaoA": "França",
    "opcaoB": "Canadá",
    "opcaoC": "Estados Unidos",
    "opcaoD": "Rússia",
    "respostaCorreta": "A) França",
    "curiosidade": "Pode parecer estranho, mas devido aos seus territórios ultramarinos, a França é oficialmente o país com mais fusos horários (12, ou 13 se considerada a reivindicação na Antártida), superando a Rússia. É uma daquelas respostas que quase toda a gente erra à primeira."
  },
  {
    "id": "GEO-011",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Lama Seca",
    "opcaoB": "Pocilga Feliz",
    "opcaoC": "Buraco Fundo",
    "opcaoD": "Chiqueiro",
    "respostaCorreta": "D) Chiqueiro",
    "curiosidade": "Chiqueiro existe mesmo em Portugal e é uma pequena localidade cujo nome costuma provocar gargalhadas quando aparece em listas de topónimos curiosos."
  },
  {
    "id": "GEO-012",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem o maior número de ilhas do mundo?",
    "opcaoA": "Japão",
    "opcaoB": "Suécia",
    "opcaoC": "Filipinas",
    "opcaoD": "Indonésia",
    "respostaCorreta": "B) Suécia",
    "curiosidade": "A Suécia possui cerca de 267 mil ilhas, embora apenas uma pequena parte seja habitada."
  },
  {
    "id": "GEO-013",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Picharada",
    "opcaoB": "Pichota",
    "opcaoC": "Picha",
    "opcaoD": "Picholas",
    "respostaCorreta": "C) Picha",
    "curiosidade": "Existe uma localidade chamada Picha, no concelho de Pedrógão Grande. O nome é antigo e não tem a origem que a maioria das pessoas imagina. 🤣 Esta é daquelas que vai fazer o chat explodir."
  },
  {
    "id": "GEO-014",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem a maior população do mundo atualmente?",
    "opcaoA": "Estados Unidos",
    "opcaoB": "Indonésia",
    "opcaoC": "China",
    "opcaoD": "Índia",
    "respostaCorreta": "D) Índia",
    "curiosidade": "Em 2023 a Índia ultrapassou oficialmente a China em população."
  },
  {
    "id": "GEO-016",
    "disciplina": "Geografia",
    "pergunta": "Qual é o lago com maior volume de água doce do planeta?",
    "opcaoA": "Lago Tanganica",
    "opcaoB": "Lago Vitória",
    "opcaoC": "Lago Baikal",
    "opcaoD": "Lago Superior",
    "respostaCorreta": "C) Lago Baikal",
    "curiosidade": "O Baikal, na Rússia, contém cerca de 20% da água doce líquida não congelada do planeta."
  },
  {
    "id": "GEO-017",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países faz fronteira com Portugal?",
    "opcaoA": "Andorra",
    "opcaoB": "Marrocos",
    "opcaoC": "Espanha",
    "opcaoD": "França",
    "respostaCorreta": "C) Espanha",
    "curiosidade": "Portugal apenas tem uma fronteira terrestre. E é com Espanha."
  },
  {
    "id": "GEO-018",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Pescoço de DVD",
    "opcaoB": "Nariz de Vinil",
    "opcaoC": "Cabeço de Vide",
    "opcaoD": "Orelha de CD",
    "respostaCorreta": "C) Cabeço de Vide",
    "curiosidade": "Cabeço de Vide pertence ao concelho de Fronteira e é conhecida pelas suas águas termais."
  },
  {
    "id": "GEO-019",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem maior área?",
    "opcaoA": "Espanha",
    "opcaoB": "Itália",
    "opcaoC": "França",
    "opcaoD": "Alemanha",
    "respostaCorreta": "C) França",
    "curiosidade": "Mesmo sem contar com territórios ultramarinos, França continua a ser o maior país da União Europeia em área."
  },
  {
    "id": "GEO-020",
    "disciplina": "Geografia",
    "pergunta": "Qual destas cidades está construída em dois continentes?",
    "opcaoA": "Atenas",
    "opcaoB": "Istambul",
    "opcaoC": "Roma",
    "opcaoD": "Viena",
    "respostaCorreta": "B) Istambul",
    "curiosidade": "Istambul é atravessada pelo estreito do Bósforo, separando Europa e Ásia."
  },
  {
    "id": "GEO-021",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Casal das Sobrinhas",
    "opcaoB": "Rua dos Cornos",
    "opcaoC": "Vale das Sogras",
    "opcaoD": "Chão das Pias",
    "respostaCorreta": "D) Chão das Pias",
    "curiosidade": "Chão das Pias existe mesmo no concelho de Ourém — o nome vem de antigas formações rochosas que lembravam pias naturais."
  },
  {
    "id": "GEO-022",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem mais vulcões ativos?",
    "opcaoA": "Japão",
    "opcaoB": "Islândia",
    "opcaoC": "Indonésia",
    "opcaoD": "Chile",
    "respostaCorreta": "C) Indonésia",
    "curiosidade": "A Indonésia tem mais de uma centena de vulcões ativos e situa-se no famoso Anel de Fogo do Pacífico."
  },
  {
    "id": "GEO-023",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem o formato geográfico mais semelhante a uma bota?",
    "opcaoA": "Itália",
    "opcaoB": "Albânia",
    "opcaoC": "Croácia",
    "opcaoD": "Grécia",
    "respostaCorreta": "A) Itália",
    "curiosidade": "É tão característico que basta um mapa sem nomes para quase toda a gente reconhecer Itália."
  },
  {
    "id": "GEO-024",
    "disciplina": "Geografia",
    "pergunta": "Qual é o rio mais longo do mundo segundo a maioria das medições atuais?",
    "opcaoA": "Yangtzé",
    "opcaoB": "Mississippi",
    "opcaoC": "Amazonas",
    "opcaoD": "Nilo",
    "respostaCorreta": "C) Amazonas",
    "curiosidade": "Durante muitos anos o Nilo foi considerado o mais longo. Estudos mais recentes atribuem essa posição ao Amazonas, embora ainda exista algum debate científico sobre o método de medição. 🎯 Nota editorial: Esta pergunta é boa para gerar conversa, mas deve ficar marcada como \"curiosidade debatida\" para evitar apresentar a resposta como absoluta."
  },
  {
    "id": "GEO-025",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é completamente rodeado por Itália?",
    "opcaoA": "San Marino",
    "opcaoB": "Andorra",
    "opcaoC": "Liechtenstein",
    "opcaoD": "Mónaco",
    "respostaCorreta": "A) San Marino",
    "curiosidade": "San Marino é um dos países mais antigos do mundo e encontra-se totalmente rodeado por território italiano."
  },
  {
    "id": "GEO-026",
    "disciplina": "Geografia",
    "pergunta": "Qual destes distritos portugueses faz fronteira com Espanha?",
    "opcaoA": "Viseu",
    "opcaoB": "Leiria",
    "opcaoC": "Aveiro",
    "opcaoD": "Portalegre",
    "respostaCorreta": "D) Portalegre",
    "curiosidade": "Portalegre faz parte da extensa fronteira luso-espanhola, conhecida como \"A Raia\"."
  },
  {
    "id": "GEO-027",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem um dragão na sua bandeira?",
    "opcaoA": "Inglaterra",
    "opcaoB": "Escócia",
    "opcaoC": "Irlanda",
    "opcaoD": "País de Gales",
    "respostaCorreta": "D) País de Gales",
    "curiosidade": "Embora faça parte do Reino Unido, o País de Gales tem uma das bandeiras mais icónicas do mundo graças ao famoso dragão vermelho."
  },
  {
    "id": "GEO-028",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países tem a maior altitude média da Europa?",
    "opcaoA": "Áustria",
    "opcaoB": "Noruega",
    "opcaoC": "Suíça",
    "opcaoD": "Andorra",
    "respostaCorreta": "D) Andorra",
    "curiosidade": "Apesar de ser um país muito pequeno, Andorra tem uma altitude média superior à da Suíça."
  },
  {
    "id": "GEO-029",
    "disciplina": "Geografia",
    "pergunta": "Qual destas localidades portuguesas existe mesmo?",
    "opcaoA": "Monte do Toucinho",
    "opcaoB": "Venda do Porco",
    "opcaoC": "Venda da Porca",
    "opcaoD": "Aldeia do Leitão",
    "respostaCorreta": "B) Venda do Porco",
    "curiosidade": "Venda do Porco existe mesmo no concelho de Leiria. Como muitos topónimos antigos, o nome está ligado a atividades rurais da época."
  },
  {
    "id": "GEO-030",
    "disciplina": "Geografia",
    "pergunta": "Qual destes países é atravessado simultaneamente pela Linha do Equador e pelo Meridiano de Greenwich?",
    "opcaoA": "Gabão",
    "opcaoB": "República do Congo",
    "opcaoC": "São Tomé e Príncipe",
    "opcaoD": "Gana",
    "respostaCorreta": "C) São Tomé e Príncipe",
    "curiosidade": "São Tomé e Príncipe é um dos raros países associados aos dois grandes referenciais geográficos, tornando-o uma excelente curiosidade para quizzes."
  },
  {
    "id": "POR-001",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente em português?",
    "opcaoA": "Espingalhar",
    "opcaoB": "Esbardalhar",
    "opcaoC": "Esgalhardar",
    "opcaoD": "Escambardar",
    "respostaCorreta": "B) Esbardalhar",
    "curiosidade": "\"Esbardalhar\" significa cair desamparadamente ou estragar algo por completo. É uma palavra reconhecida nos principais dicionários da língua portuguesa."
  },
  {
    "id": "POR-002",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Ir dar uma volta ao bilhar grande",
    "opcaoB": "Ir dormir para a sombra do poste",
    "opcaoC": "Ir bater ao ferro frio",
    "opcaoD": "Ir regar o cimento",
    "respostaCorreta": "A) Ir dar uma volta ao bilhar grande",
    "curiosidade": "\"Ir dar uma volta ao bilhar grande\" é uma forma popular e humorística de dizer que alguém morreu."
  },
  {
    "id": "POR-003",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Lambão",
    "opcaoB": "Lambosoide",
    "opcaoC": "Lambisco",
    "opcaoD": "Lambarudo",
    "respostaCorreta": "A) Lambão",
    "curiosidade": "\"Lambão\" descreve alguém muito guloso ou comilão e é uma palavra perfeitamente válida em português."
  },
  {
    "id": "POR-004",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras portuguesas tem origem árabe?",
    "opcaoA": "Cadeira",
    "opcaoB": "Janela",
    "opcaoC": "Almofada",
    "opcaoD": "Mesa",
    "respostaCorreta": "C) Almofada",
    "curiosidade": "Centenas de palavras portuguesas começam por \"al-\" precisamente por terem origem no árabe, como almofada, alface, aldeia e alfândega."
  },
  {
    "id": "POR-005",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Ficar a contar sardinhas",
    "opcaoB": "Ficar a apanhar relva",
    "opcaoC": "Ficar a ver navios",
    "opcaoD": "Ficar debaixo do sino",
    "respostaCorreta": "C) Ficar a ver navios",
    "curiosidade": "A expressão \"ficar a ver navios\" significa ficar desiludido ou sem aquilo que esperava."
  },
  {
    "id": "POR-006",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Escabedar",
    "opcaoB": "Escafundrar",
    "opcaoC": "Escapedrar",
    "opcaoD": "Escafeder",
    "respostaCorreta": "D) Escafeder",
    "curiosidade": "\"Escafeder-se\" significa fugir rapidamente ou desaparecer sem deixar rasto."
  },
  {
    "id": "POR-007",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras portuguesas designa uma chuva muito fraca?",
    "opcaoA": "Chuveta",
    "opcaoB": "Chuvisco",
    "opcaoC": "Chuvalho",
    "opcaoD": "Chuviscoide",
    "respostaCorreta": "B) Chuvisco",
    "curiosidade": "\"Chuvisco\" é o nome correto para uma precipitação muito leve e contínua."
  },
  {
    "id": "POR-008",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Meter a viola no saco",
    "opcaoB": "Dobrar o tambor",
    "opcaoC": "Guardar a guitarra no bolso",
    "opcaoD": "Enrolar a concertina",
    "respostaCorreta": "A) Meter a viola no saco",
    "curiosidade": "\"Meter a viola no saco\" significa desistir ou calar-se depois de perceber que perdeu a razão."
  },
  {
    "id": "POR-009",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Trambelho",
    "opcaoB": "Trambolho",
    "opcaoC": "Trambelisco",
    "opcaoD": "Trambalhão",
    "respostaCorreta": "B) Trambolho",
    "curiosidade": "\"Trambolho\" pode referir-se a um objeto grande, pesado ou pouco prático, mas também é usado para descrever alguém de forma bem-humorada."
  },
  {
    "id": "POR-010",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe e significa \"confusão ou desordem\"?",
    "opcaoA": "Arregançoide",
    "opcaoB": "Arreliaço",
    "opcaoC": "Algarito",
    "opcaoD": "Alarido",
    "respostaCorreta": "D) Alarido",
    "curiosidade": "\"Alarido\" descreve uma grande algazarra ou confusão, sendo uma palavra bastante antiga que continua presente no português atual."
  },
  {
    "id": "POR-011",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Estarrecalho",
    "opcaoB": "Estarrecinho",
    "opcaoC": "Estarrecido",
    "opcaoD": "Estarreço",
    "respostaCorreta": "C) Estarrecido",
    "curiosidade": "\"Estarrecido\" significa que sente grande medo, susto ou terror — usado em situações de choque ou pavor intenso. \"Escagaitado\" não estava confirmado em nenhum dicionário oficial e foi substituído por \"Estarrecido\" (confirmado no Priberam). Distratores também substituídos."
  },
  {
    "id": "POR-012",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Pôr o burro em cima da bicicleta",
    "opcaoB": "Pôr as galinhas atrás do trator",
    "opcaoC": "Pôr os bois à frente da carroça",
    "opcaoD": "Pôr a cabra ao volante",
    "respostaCorreta": "C) Pôr os bois à frente da carroça",
    "curiosidade": "\"Pôr os bois à frente da carroça\" significa inverter a ordem lógica das coisas."
  },
  {
    "id": "POR-013",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Badarrão",
    "opcaoB": "Badaroco",
    "opcaoC": "Badanelo",
    "opcaoD": "Badameco",
    "respostaCorreta": "D) Badameco",
    "curiosidade": "\"Badameco\" é uma palavra usada para descrever alguém parvo, pateta ou pouco inteligente, normalmente em tom de brincadeira."
  },
  {
    "id": "POR-014",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Andar ao candeeiro",
    "opcaoB": "Andar à nora",
    "opcaoC": "Andar à pá",
    "opcaoD": "Andar ao escadote",
    "respostaCorreta": "B) Andar à nora",
    "curiosidade": "\"Andar à nora\" significa estar completamente perdido ou confuso."
  },
  {
    "id": "POR-015",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Fanfarrudo",
    "opcaoB": "Fanfarrão",
    "opcaoC": "Fanfarral",
    "opcaoD": "Fanfarrentoide",
    "respostaCorreta": "B) Fanfarrão",
    "curiosidade": "Um fanfarrão é alguém que gosta de se gabar ou exagerar as próprias capacidades."
  },
  {
    "id": "POR-016",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Quem tem cotovelos vai a Faro",
    "opcaoB": "Quem tem boca vai a Roma",
    "opcaoC": "Quem tem barriga vai a Coimbra",
    "opcaoD": "Quem tem pernas vai a Braga",
    "respostaCorreta": "B) Quem tem boca vai a Roma",
    "curiosidade": "Originalmente, esta expressão queria dizer que quem pergunta consegue encontrar o caminho."
  },
  {
    "id": "POR-017",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Zarolhiceiro",
    "opcaoB": "Zarolhudo",
    "opcaoC": "Zarolhão",
    "opcaoD": "Zarolho",
    "respostaCorreta": "D) Zarolho",
    "curiosidade": "\"Zarolho\" descreve alguém com estrabismo ou com um olho desalinhado. É uma palavra antiga que continua perfeitamente válida."
  },
  {
    "id": "POR-018",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Ficar em sopa de nabiças",
    "opcaoB": "Ficar em caldo verde",
    "opcaoC": "Ficar em águas de bacalhau",
    "opcaoD": "Ficar em arroz malandro",
    "respostaCorreta": "C) Ficar em águas de bacalhau",
    "curiosidade": "Quando algo \"fica em águas de bacalhau\", significa que acaba por não dar em nada."
  },
  {
    "id": "POR-019",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Pataralha",
    "opcaoB": "Patarata",
    "opcaoC": "Patareca",
    "opcaoD": "Patarica",
    "respostaCorreta": "B) Patarata",
    "curiosidade": "\"Patarata\" significa uma mentira, disparate ou conversa sem sentido."
  },
  {
    "id": "POR-020",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Estar com a meia na cabeça",
    "opcaoB": "Estar com a colher no bolso",
    "opcaoC": "Estar com a frigideira ao ombro",
    "opcaoD": "Estar com a corda ao pescoço",
    "respostaCorreta": "D) Estar com a corda ao pescoço",
    "curiosidade": "\"Estar com a corda ao pescoço\" significa estar numa situação difícil, normalmente por falta de dinheiro ou por estar sob grande pressão."
  },
  {
    "id": "POR-021",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Bugarrada",
    "opcaoB": "Bugalhanga",
    "opcaoC": "Buguelhenga",
    "opcaoD": "Bugiganga",
    "respostaCorreta": "D) Bugiganga",
    "curiosidade": "\"Bugiganga\" é uma palavra perfeitamente válida e refere-se a um objeto sem grande valor ou utilidade."
  },
  {
    "id": "POR-022",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Fazer uma cabrinha",
    "opcaoB": "Fazer um porquinho",
    "opcaoC": "Fazer um carneirinho",
    "opcaoD": "Fazer uma vaquinha",
    "respostaCorreta": "D) Fazer uma vaquinha",
    "curiosidade": "\"Fazer uma vaquinha\" significa juntar dinheiro entre várias pessoas para um objetivo comum."
  },
  {
    "id": "POR-023",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Catrefada",
    "opcaoB": "Catrilhada",
    "opcaoC": "Catarrafada",
    "opcaoD": "Catrapada",
    "respostaCorreta": "A) Catrefada",
    "curiosidade": "Uma \"catrefada\" significa uma grande quantidade de alguma coisa."
  },
  {
    "id": "POR-024",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Fanico",
    "opcaoB": "Faniscalho",
    "opcaoC": "Fanecada",
    "opcaoD": "Fanecaço",
    "respostaCorreta": "A) Fanico",
    "curiosidade": "\"Dar um fanico\" significa desmaiar ou sentir-se muito mal, sendo uma expressão muito usada em Portugal."
  },
  {
    "id": "POR-025",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Estar nas cortinas",
    "opcaoB": "Estar nas lonas",
    "opcaoC": "Estar nos tapetes",
    "opcaoD": "Estar nos lençóis",
    "respostaCorreta": "B) Estar nas lonas",
    "curiosidade": "\"Estar nas lonas\" significa estar sem dinheiro ou numa situação financeira complicada."
  },
  {
    "id": "POR-026",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Geringonça",
    "opcaoB": "Geringota",
    "opcaoC": "Geringolha",
    "opcaoD": "Geringalha",
    "respostaCorreta": "A) Geringonça",
    "curiosidade": "Originalmente, \"geringonça\" designava uma máquina ou objeto improvisado e pouco fiável."
  },
  {
    "id": "POR-027",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões populares existe mesmo?",
    "opcaoA": "Rebeubéu, pardais ao ninho!",
    "opcaoB": "Chorar guardanapos ao vento",
    "opcaoC": "Enrolar bigodes na chaminé",
    "opcaoD": "Guardar patins no sótão da lua",
    "respostaCorreta": "A) Rebeubéu, pardais ao ninho!",
    "curiosidade": "\"Rebeubéu, pardais ao ninho!\" é uma expressão antiga que significa grande alvoroço ou confusão — ficou também conhecida por um programa de rádio/TV de Herman José com o mesmo nome. \"Rebéubéu\" não existe como palavra isolada em dicionário — só existe dentro da expressão fixa \"Rebeubéu, pardais ao ninho!\". Pergunta convertida de \"Palavras\" para \"Expressões\"."
  },
  {
    "id": "POR-028",
    "disciplina": "Português",
    "pergunta": "Qual destas expressões existe mesmo?",
    "opcaoA": "Não perceber courgette",
    "opcaoB": "Não perceber nabiça",
    "opcaoC": "Não perceber feijoada",
    "opcaoD": "Não perceber patavina",
    "respostaCorreta": "D) Não perceber patavina",
    "curiosidade": "\"Não perceber patavina\" significa não perceber absolutamente nada de determinado assunto."
  },
  {
    "id": "POR-029",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Alarvudo",
    "opcaoB": "Alarvito",
    "opcaoC": "Alarvão",
    "opcaoD": "Alarve",
    "respostaCorreta": "D) Alarve",
    "curiosidade": "\"Alarve\" designa uma pessoa rude ou mal-educada. Curiosamente, a palavra vem de \"árabe\", devido à forma como os mouros eram vistos na Idade Média."
  },
  {
    "id": "POR-030",
    "disciplina": "Português",
    "pergunta": "Qual destas palavras existe oficialmente?",
    "opcaoA": "Badagarra",
    "opcaoB": "Badagaio",
    "opcaoC": "Badagueco",
    "opcaoD": "Badagalho",
    "respostaCorreta": "B) Badagaio",
    "curiosidade": "\"Badagaio\" significa tontura, vertigem ou crise nervosa — não uma pessoa magra, ao contrário do que às vezes se pensa. o \"Sabias que\" original descrevia mal a palavra (dizia \"pessoa magra e debilitada\"). Significado correto: tontura/vertigem/crise nervosa."
  },
  {
    "id": "HIS-002",
    "disciplina": "História",
    "pergunta": "Qual destas profissões já existiu oficialmente na corte portuguesa?",
    "opcaoA": "Dobrador Oficial de Capas",
    "opcaoB": "Afinador da Coroa",
    "opcaoC": "Aparador de Barbas Reais",
    "opcaoD": "Limpador de Penicos do Rei",
    "respostaCorreta": "D) Limpador de Penicos do Rei",
    "curiosidade": "As cortes reais tinham dezenas de cargos que hoje parecem absurdos. O tratamento dos aposentos e dos utensílios pessoais do rei fazia parte da estrutura oficial da Casa Real."
  },
  {
    "id": "HIS-003",
    "disciplina": "História",
    "pergunta": "Qual destes animais recebeu uma patente militar durante a Segunda Guerra Mundial?",
    "opcaoA": "Um urso",
    "opcaoB": "Um burro",
    "opcaoC": "Um pombo-correio",
    "opcaoD": "Um cão",
    "respostaCorreta": "D) Um cão",
    "curiosidade": "Vários cães foram oficialmente condecorados por atos de coragem durante a guerra. Alguns receberam patentes honorárias e medalhas pelo serviço prestado."
  },
  {
    "id": "HIS-004",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido como \"O Venturoso\"?",
    "opcaoA": "D. Manuel I",
    "opcaoB": "D. João II",
    "opcaoC": "D. Duarte",
    "opcaoD": "D. Dinis",
    "respostaCorreta": "A) D. Manuel I",
    "curiosidade": "D. Manuel I reinou numa das épocas mais prósperas da História de Portugal, coincidindo com o auge dos Descobrimentos."
  },
  {
    "id": "HIS-005",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um país declarou guerra à Lua.",
    "opcaoB": "Dois países estiveram oficialmente em guerra durante menos de uma hora.",
    "opcaoC": "Um rei declarou guerra ao próprio exército.",
    "opcaoD": "Um país declarou guerra ao Oceano Atlântico.",
    "respostaCorreta": "B) Dois países estiveram oficialmente em guerra durante menos de uma hora.",
    "curiosidade": "A Guerra Anglo-Zanzibar (1896) durou cerca de 38 minutos, sendo considerada a guerra mais curta da História."
  },
  {
    "id": "HIS-006",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Cleópatra viveu mais perto da criação do iPhone do que da construção das pirâmides.",
    "opcaoB": "Os vikings usavam capacetes com cornos.",
    "opcaoC": "Napoleão era invulgarmente baixo.",
    "opcaoD": "Nero tocava violino enquanto Roma ardia.",
    "respostaCorreta": "A) Cleópatra viveu mais perto da criação do iPhone do que da construção das pirâmides.",
    "curiosidade": "As Grandes Pirâmides tinham mais de 2.000 anos quando Cleópatra nasceu. Ela viveu cronologicamente muito mais perto dos dias de hoje do que da sua construção. 🤣 Esta costuma explodir cabeças."
  },
  {
    "id": "HIS-007",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido por \"o Lavrador\"?",
    "opcaoA": "D. João I",
    "opcaoB": "D. Sancho II",
    "opcaoC": "D. Dinis",
    "opcaoD": "D. Pedro I",
    "respostaCorreta": "C) D. Dinis",
    "curiosidade": "Além de incentivar a agricultura, D. Dinis mandou plantar o Pinhal de Leiria, que viria mais tarde a fornecer madeira para a construção naval portuguesa."
  },
  {
    "id": "HIS-008",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um Papa foi astronauta.",
    "opcaoB": "Um rei francês casou com uma estátua.",
    "opcaoC": "Um faraó proibiu as pirâmides.",
    "opcaoD": "Um imperador romano nomeou o seu cavalo para um cargo político.",
    "respostaCorreta": "D) Um imperador romano nomeou o seu cavalo para um cargo político.",
    "curiosidade": "O imperador Calígula terá demonstrado intenção de nomear o seu cavalo Incitatus para um cargo elevado, embora os historiadores discutam se foi uma provocação política ou um facto literal. 🎯 Excelente pergunta para gerar discussão."
  },
  {
    "id": "HIS-009",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses foi assassinado em Lisboa?",
    "opcaoA": "D. Carlos I",
    "opcaoB": "D. Pedro V",
    "opcaoC": "D. Manuel II",
    "opcaoD": "D. Luís I",
    "respostaCorreta": "A) D. Carlos I",
    "curiosidade": "D. Carlos I foi assassinado em 1908, no Terreiro do Paço, num dos acontecimentos mais marcantes da história da monarquia portuguesa."
  },
  {
    "id": "HIS-010",
    "disciplina": "História",
    "pergunta": "Qual destes países teve um cidadão comum que se autoproclamou \"Imperador\" no século XIX, e foi tratado como celebridade local mesmo sem ter poder nenhum?",
    "opcaoA": "Brasil",
    "opcaoB": "Canadá",
    "opcaoC": "Estados Unidos",
    "opcaoD": "Austrália",
    "respostaCorreta": "C) Estados Unidos",
    "curiosidade": "Joshua Norton autoproclamou-se \"Imperador dos Estados Unidos\" em São Francisco, em 1859. A cidade tratava-o como celebridade — chegou a emitir a sua própria moeda, aceite em vários restaurantes e estabelecimentos locais."
  },
  {
    "id": "HIS-011",
    "disciplina": "História",
    "pergunta": "Qual destes impostos existiu mesmo em Portugal?",
    "opcaoA": "Imposto sobre chapéus de palha",
    "opcaoB": "Imposto das janelas",
    "opcaoC": "Imposto dos galos",
    "opcaoD": "Imposto sobre barbas",
    "respostaCorreta": "B) Imposto das janelas",
    "curiosidade": "O chamado \"imposto das janelas\" existiu em vários países europeus, incluindo Portugal. Como resultado, muitas casas antigas têm janelas tapadas com tijolo para evitar pagar mais imposto."
  },
  {
    "id": "HIS-012",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Napoleão media pouco mais de 1,50 m.",
    "opcaoB": "Em Salém, os condenados foram enforcados, não queimados.",
    "opcaoC": "Os vikings usavam capacetes com cornos.",
    "opcaoD": "As bruxas de Salém foram queimadas.",
    "respostaCorreta": "B) Em Salém, os condenados foram enforcados, não queimados.",
    "curiosidade": "Os vikings não usavam capacetes com cornos, Napoleão tinha uma altura normal para a época e, em Salém, os condenados foram enforcados, não queimados."
  },
  {
    "id": "HIS-013",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "A Austrália entrou em guerra contra emas.",
    "opcaoB": "Um castelo foi conquistado por ovelhas.",
    "opcaoC": "Um exército perdeu uma batalha porque foi atacado por... coelhos.",
    "opcaoD": "Um país declarou guerra a aves marinhas.",
    "respostaCorreta": "A) A Austrália entrou em guerra contra emas.",
    "curiosidade": "Em 1932, a Austrália lançou uma operação militar para controlar milhares de emas que destruíam plantações. Ficou conhecida como a Grande Guerra das Emas... e as emas \"ganharam\"."
  },
  {
    "id": "HIS-014",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses ficou conhecido como \"O Justiceiro\"?",
    "opcaoA": "D. Sancho I",
    "opcaoB": "D. Pedro I",
    "opcaoC": "D. Manuel II",
    "opcaoD": "D. João II",
    "respostaCorreta": "B) D. Pedro I",
    "curiosidade": "D. Pedro I mandou perseguir os assassinos de Inês de Castro e, segundo a tradição, obrigou membros da corte a beijar a mão da rainha já depois de morta. Embora alguns detalhes sejam debatidos, a história tornou-se uma das mais famosas de Portugal."
  },
  {
    "id": "HIS-015",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei foi condenado por um tribunal moderno.",
    "opcaoB": "Um Papa foi julgado... depois de morrer.",
    "opcaoC": "Um faraó foi preso.",
    "opcaoD": "Um imperador vendeu o próprio país.",
    "respostaCorreta": "B) Um Papa foi julgado... depois de morrer.",
    "curiosidade": "No chamado Sínodo do Cadáver (897 d.C.), o corpo do Papa Formoso foi exumado, vestido com roupas papais e submetido a julgamento. 🤣 Parece inventado. Não é."
  },
  {
    "id": "HIS-016",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei português morreu depois de comer um doce.",
    "opcaoB": "Um rei português morreu num desastre de carruagem.",
    "opcaoC": "Um rei português morreu esmagado por uma árvore.",
    "opcaoD": "Um rei português morreu por causa de uma queda de cavalo.",
    "respostaCorreta": "B) Um rei português morreu num desastre de carruagem.",
    "curiosidade": "D. José I escapou, mas o acidente de carruagem em que seguia teve enorme impacto político e ajudou a desencadear acontecimentos ligados ao famoso Processo dos Távoras."
  },
  {
    "id": "HIS-017",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um piloto aterrou na Lua por engano.",
    "opcaoB": "Um tanque afundou um porta-aviões.",
    "opcaoC": "Um submarino atravessou o deserto.",
    "opcaoD": "Um soldado japonês continuou a combater muito tempo depois do fim da Segunda Guerra Mundial.",
    "respostaCorreta": "D) Um soldado japonês continuou a combater muito tempo depois do fim da Segunda Guerra Mundial.",
    "curiosidade": "Hiroo Onoda só se rendeu em 1974, porque acreditava que a guerra ainda não tinha terminado."
  },
  {
    "id": "HIS-018",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses morreu sem deixar descendentes legítimos, originando uma crise sucessória?",
    "opcaoA": "D. João IV",
    "opcaoB": "D. Afonso Henriques",
    "opcaoC": "D. Pedro IV",
    "opcaoD": "D. Sebastião",
    "respostaCorreta": "D) D. Sebastião",
    "curiosidade": "O desaparecimento de D. Sebastião abriu caminho para a crise de 1580 e para a União Ibérica."
  },
  {
    "id": "HIS-019",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "O presidente dos Estados Unidos já ficou preso numa banheira.",
    "opcaoB": "Um imperador chinês proibiu arroz.",
    "opcaoC": "Um rei de Inglaterra perdeu uma guerra às pombas.",
    "opcaoD": "Júlio César tinha medo de cavalos.",
    "respostaCorreta": "A) O presidente dos Estados Unidos já ficou preso numa banheira.",
    "curiosidade": "William Howard Taft era um homem de grande porte e ficou famoso por uma história em que alegadamente ficou preso na banheira da Casa Branca. Alguns historiadores discutem os detalhes, mas a história tornou-se lendária."
  },
  {
    "id": "HIS-020",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "A Grande Muralha da China é visível da Lua a olho nu.",
    "opcaoB": "O Titanic foi o maior desastre marítimo da História.",
    "opcaoC": "Einstein era excelente a Matemática desde muito jovem.",
    "opcaoD": "Einstein era péssimo a Matemática.",
    "respostaCorreta": "C) Einstein era excelente a Matemática desde muito jovem.",
    "curiosidade": "O Titanic não foi o maior desastre marítimo em número de vítimas, Einstein era excelente a Matemática desde jovem e a Grande Muralha não é visível da Lua a olho nu."
  },
  {
    "id": "HIS-021",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "O ketchup nasceu em França.",
    "opcaoB": "A Coca-Cola já foi vendida como medicamento.",
    "opcaoC": "A pizza foi inventada na Alemanha.",
    "opcaoD": "A Nutella foi criada para alimentar soldados.",
    "respostaCorreta": "B) A Coca-Cola já foi vendida como medicamento.",
    "curiosidade": "Quando foi criada em 1886, a Coca-Cola era vendida nas farmácias como um tónico medicinal."
  },
  {
    "id": "HIS-022",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações sobre D. Afonso Henriques é verdadeira?",
    "opcaoA": "Foi armado cavaleiro aos 30 anos.",
    "opcaoB": "Foi rei de Espanha durante um dia.",
    "opcaoC": "Foi preso pela própria mãe.",
    "opcaoD": "Lutou numa cruzada no Japão.",
    "respostaCorreta": "C) Foi preso pela própria mãe.",
    "curiosidade": "Durante o conflito entre D. Teresa e D. Afonso Henriques, há relatos de que este chegou a ser detido por ordem da própria mãe antes de consolidar o seu poder."
  },
  {
    "id": "HIS-023",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um rei morreu porque um macaco o mordeu.",
    "opcaoB": "Um czar morreu a dançar.",
    "opcaoC": "Um imperador morreu engasgado com uma cebola.",
    "opcaoD": "Um faraó morreu a jogar xadrez.",
    "respostaCorreta": "A) Um rei morreu porque um macaco o mordeu.",
    "curiosidade": "O rei Alexandre da Grécia morreu em 1920 depois de desenvolver uma infeção causada pela mordida de um macaco durante uma tentativa de separar uma luta entre animais. 🤣 Parece argumento de filme."
  },
  {
    "id": "HIS-024",
    "disciplina": "História",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Os gladiadores lutavam sempre até à morte.",
    "opcaoB": "Muitos combates de gladiadores terminavam sem morte, por serem caros de treinar.",
    "opcaoC": "As pirâmides foram construídas por escravos.",
    "opcaoD": "Júlio César nasceu por cesariana.",
    "respostaCorreta": "B) Muitos combates de gladiadores terminavam sem morte, por serem caros de treinar.",
    "curiosidade": "Os trabalhadores das pirâmides eram, em grande parte, artesãos e operários pagos; Júlio César não nasceu por cesariana; e muitos combates de gladiadores terminavam sem morte porque eram caros de treinar."
  },
  {
    "id": "HIS-025",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Uma vaca recebeu um Nobel.",
    "opcaoB": "Um pinguim comandou um navio.",
    "opcaoC": "Um urso serviu oficialmente no exército.",
    "opcaoD": "Um elefante foi eleito presidente.",
    "respostaCorreta": "C) Um urso serviu oficialmente no exército.",
    "curiosidade": "Wojtek, um urso-pardo adotado por soldados polacos durante a Segunda Guerra Mundial, recebeu estatuto militar e ajudava a transportar caixas de munições. ❤️ Uma das histórias mais incríveis da guerra."
  },
  {
    "id": "HIS-026",
    "disciplina": "História",
    "pergunta": "Qual destes reis portugueses teve o cognome \"O Formoso\"?",
    "opcaoA": "D. Duarte",
    "opcaoB": "D. João III",
    "opcaoC": "D. Fernando I",
    "opcaoD": "D. Sancho II",
    "respostaCorreta": "C) D. Fernando I",
    "curiosidade": "D. Fernando I ficou conhecido como \"O Formoso\", embora o seu reinado tenha sido marcado por conflitos e instabilidade."
  },
  {
    "id": "HIS-027",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um piloto sobreviveu a cinco quedas na Lua.",
    "opcaoB": "Um homem sobreviveu às duas bombas atómicas do Japão.",
    "opcaoC": "Um marinheiro deu a volta ao mundo num submarino a remos.",
    "opcaoD": "Um astronauta perdeu-se em Marte.",
    "respostaCorreta": "B) Um homem sobreviveu às duas bombas atómicas do Japão.",
    "curiosidade": "Tsutomu Yamaguchi sobreviveu à bomba de Hiroshima, regressou a Nagasaki... e sobreviveu também à segunda explosão. 🤯 Esta costuma deixar toda a gente em silêncio."
  },
  {
    "id": "HIS-028",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um castelo rendeu-se a um acordeão.",
    "opcaoB": "Um país perdeu uma guerra porque acabou o café.",
    "opcaoC": "Um rei assinou um tratado com um golfinho.",
    "opcaoD": "Um exército perdeu porque confundiu o próprio barulho com um ataque inimigo.",
    "respostaCorreta": "D) Um exército perdeu porque confundiu o próprio barulho com um ataque inimigo.",
    "curiosidade": "Na Batalha de Karánsebes (1788), tropas austríacas entraram em pânico e dispararam umas contra as outras após uma sequência de mal-entendidos e confusão durante a noite."
  },
  {
    "id": "HIS-029",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Link começou por ser um pirata.",
    "opcaoB": "Pac-Man ia chamar-se Pizza Boy.",
    "opcaoC": "O nome original do Mario era Jumpman.",
    "opcaoD": "Sonic chamava-se Blue Rabbit.",
    "respostaCorreta": "C) O nome original do Mario era Jumpman.",
    "curiosidade": "Na sua primeira aparição em Donkey Kong (1981), Mario era conhecido apenas como Jumpman. 🎮 Esta entra muito bem na disciplina."
  },
  {
    "id": "HIS-030",
    "disciplina": "História",
    "pergunta": "Qual destes acontecimentos aconteceu mesmo?",
    "opcaoA": "Um imperador morreu num concurso de dança.",
    "opcaoB": "Um rei morreu por rir demasiado.",
    "opcaoC": "Um faraó morreu a escorregar numa banana.",
    "opcaoD": "Um Papa morreu a jogar cartas.",
    "respostaCorreta": "B) Um rei morreu por rir demasiado.",
    "curiosidade": "Segundo várias fontes históricas, o rei Martim I de Aragão morreu em 1410 após uma crise provocada por uma combinação de problemas digestivos e um ataque de riso desencadeado por uma piada do seu bobo da corte. A história é debatida nos detalhes, mas tornou-se uma das mortes mais insólitas atribuídas a um monarca."
  },
  {
    "id": "SCI-001",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais faz cocó em forma de cubo?",
    "opcaoA": "Castor",
    "opcaoB": "Coala",
    "opcaoC": "Texugo",
    "opcaoD": "Wombat",
    "respostaCorreta": "D) Wombat",
    "curiosidade": "O intestino do wombat comprime os excrementos de forma tão específica que eles saem... em cubos. Isto impede que rolem pelas encostas e ajuda a marcar território. 🤣 Sim. A Natureza decidiu fazer isto."
  },
  {
    "id": "SCI-002",
    "disciplina": "Ciência",
    "pergunta": "Qual destas partes do corpo humano continua a crescer durante praticamente toda a vida?",
    "opcaoA": "Rótulas",
    "opcaoB": "Cotovelos",
    "opcaoC": "Nariz e orelhas",
    "opcaoD": "Dentes",
    "respostaCorreta": "C) Nariz e orelhas",
    "curiosidade": "Na realidade, o que continua a mudar é sobretudo a cartilagem e a pele, dando a sensação de que o nariz e as orelhas \"crescem\" ao longo da vida."
  },
  {
    "id": "SCI-003",
    "disciplina": "Ciência",
    "pergunta": "Segundo astronautas, a que cheira o espaço?",
    "opcaoA": "Pipocas",
    "opcaoB": "Carne grelhada e metal queimado",
    "opcaoC": "Chocolate",
    "opcaoD": "Gasolina",
    "respostaCorreta": "B) Carne grelhada e metal queimado",
    "curiosidade": "Depois das caminhadas espaciais, vários astronautas descreveram um cheiro semelhante a metal quente, carne grelhada ou pólvora."
  },
  {
    "id": "SCI-004",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue sobreviver ao vácuo do espaço durante algum tempo?",
    "opcaoA": "Barata",
    "opcaoB": "Escorpião",
    "opcaoC": "Polvo",
    "opcaoD": "Tardígrado",
    "respostaCorreta": "D) Tardígrado",
    "curiosidade": "Os tardígrados conseguem entrar num estado de criptobiose e resistir ao vácuo, radiação extrema e temperaturas absurdas. São praticamente os \"bosses finais\" da biologia."
  },
  {
    "id": "SCI-005",
    "disciplina": "Ciência",
    "pergunta": "Qual destes metais pode derreter na palma da tua mão?",
    "opcaoA": "Ferro",
    "opcaoB": "Titânio",
    "opcaoC": "Gálio",
    "opcaoD": "Alumínio",
    "respostaCorreta": "C) Gálio",
    "curiosidade": "O gálio derrete por volta dos 30 °C. Basta segurá-lo alguns minutos para começar a transformar-se em líquido."
  },
  {
    "id": "SCI-006",
    "disciplina": "Ciência",
    "pergunta": "Qual destes órgãos consegue regenerar grande parte do seu tecido?",
    "opcaoA": "Fígado",
    "opcaoB": "Coração",
    "opcaoC": "Pulmão",
    "opcaoD": "Rim",
    "respostaCorreta": "A) Fígado",
    "curiosidade": "O fígado é um dos poucos órgãos humanos com uma extraordinária capacidade de regeneração, razão pela qual é possível fazer transplantes parciais."
  },
  {
    "id": "SCI-007",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem três corações?",
    "opcaoA": "Tubarão",
    "opcaoB": "Baleia",
    "opcaoC": "Polvo",
    "opcaoD": "Lula-gigante",
    "respostaCorreta": "C) Polvo",
    "curiosidade": "Dois corações enviam sangue para as guelras e um distribui sangue pelo resto do corpo."
  },
  {
    "id": "SCI-008",
    "disciplina": "Ciência",
    "pergunta": "Qual destes líquidos quentes congela, em determinadas condições, mais depressa do que um líquido frio?",
    "opcaoA": "Água",
    "opcaoB": "Vinagre",
    "opcaoC": "Azeite",
    "opcaoD": "Leite",
    "respostaCorreta": "A) Água",
    "curiosidade": "É o chamado Efeito Mpemba. Ainda hoje existem debates sobre os mecanismos exatos, mas o fenómeno já foi observado experimentalmente em determinadas condições."
  },
  {
    "id": "SCI-009",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dormir de olhos abertos?",
    "opcaoA": "Canguru",
    "opcaoB": "Panda",
    "opcaoC": "Cavalo",
    "opcaoD": "Tigre",
    "respostaCorreta": "C) Cavalo",
    "curiosidade": "Os cavalos conseguem descansar de pé graças a um sistema de bloqueio das pernas. Além disso, podem permanecer vigilantes durante parte do descanso."
  },
  {
    "id": "SCI-010",
    "disciplina": "Ciência",
    "pergunta": "Qual destes fenómenos acontece mesmo?",
    "opcaoA": "Existem vulcões que expelem granizo em vez de lava.",
    "opcaoB": "Há nuvens em forma de donut fixas sobre o Pólo Sul.",
    "opcaoC": "Há desertos onde a areia muda de cor todos os dias.",
    "opcaoD": "Chove peixe.",
    "respostaCorreta": "D) Chove peixe.",
    "curiosidade": "Sim! Já foram registadas \"chuvas\" de peixes associadas a tornados que erguem cardumes de lagos/rios e os deixam cair longe. (Nota: existem mesmo correntes densas tipo \"rios\" no fundo do mar e lagos cor-de-rosa por microrganismos — factos reais que podem voltar como perguntas à parte.)"
  },
  {
    "id": "SCI-011",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue mudar de sexo ao longo da vida?",
    "opcaoA": "Águia",
    "opcaoB": "Peixe-palhaço",
    "opcaoC": "Cavalo",
    "opcaoD": "Lobo",
    "respostaCorreta": "B) Peixe-palhaço",
    "curiosidade": "Nos grupos de peixes-palhaço, se a fêmea dominante morrer, o macho dominante pode mudar de sexo e assumir o seu lugar."
  },
  {
    "id": "SCI-012",
    "disciplina": "Ciência",
    "pergunta": "Qual destes órgãos não sente dor?",
    "opcaoA": "Cérebro",
    "opcaoB": "Fígado",
    "opcaoC": "Estômago",
    "opcaoD": "Pulmão",
    "respostaCorreta": "A) Cérebro",
    "curiosidade": "O cérebro não possui recetores de dor. É por isso que certas cirurgias cerebrais podem ser realizadas com o paciente acordado."
  },
  {
    "id": "SCI-013",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "No espaço o cabelo deixa de crescer.",
    "opcaoB": "No espaço ninguém consegue arrotar normalmente.",
    "opcaoC": "No espaço perde-se o sentido do olfato.",
    "opcaoD": "No espaço deixa-se de pestanejar.",
    "respostaCorreta": "B) No espaço ninguém consegue arrotar normalmente.",
    "curiosidade": "Sem gravidade, os gases e os líquidos no estômago não se separam da mesma forma, tornando o arroto... uma experiência completamente diferente."
  },
  {
    "id": "SCI-014",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dar um murro para atordoar a presa?",
    "opcaoA": "Camarão-louva-a-deus",
    "opcaoB": "Lagosta",
    "opcaoC": "Caranguejo",
    "opcaoD": "Camarão-pistola",
    "respostaCorreta": "A) Camarão-louva-a-deus",
    "curiosidade": "O camarão-louva-a-deus desfere golpes tão rápidos que cria pequenas bolhas de cavitação. O impacto é suficiente para partir conchas e até partir vidro fino de aquários."
  },
  {
    "id": "SCI-015",
    "disciplina": "Ciência",
    "pergunta": "Qual destes alimentos praticamente nunca se estraga?",
    "opcaoA": "Mel",
    "opcaoB": "Açúcar",
    "opcaoC": "Sal",
    "opcaoD": "Arroz",
    "respostaCorreta": "A) Mel",
    "curiosidade": "Já foi encontrado mel em túmulos do Antigo Egito com milhares de anos que continuava próprio para consumo, desde que estivesse bem preservado."
  },
  {
    "id": "SCI-016",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue dormir com metade do cérebro de cada vez?",
    "opcaoA": "Canguru",
    "opcaoB": "Golfinho",
    "opcaoC": "Gorila",
    "opcaoD": "Tigre",
    "respostaCorreta": "B) Golfinho",
    "curiosidade": "Os golfinhos deixam apenas um hemisfério cerebral a dormir, permitindo-lhes continuar a respirar e vigiar predadores."
  },
  {
    "id": "SCI-017",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O cabelo continua a crescer depois da morte.",
    "opcaoB": "Os adultos têm mais dentes que os bebés.",
    "opcaoC": "Os bebés nascem com mais ossos do que um adulto.",
    "opcaoD": "O coração para durante um espirro.",
    "respostaCorreta": "C) Os bebés nascem com mais ossos do que um adulto.",
    "curiosidade": "Os bebés têm cerca de 270 ossos. À medida que crescem, muitos fundem-se, ficando um adulto com cerca de 206."
  },
  {
    "id": "SCI-018",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue sobreviver vários meses sem comer?",
    "opcaoA": "Cavalo",
    "opcaoB": "Leão",
    "opcaoC": "Pinguim-imperador",
    "opcaoD": "Lobo",
    "respostaCorreta": "C) Pinguim-imperador",
    "curiosidade": "Durante a incubação dos ovos, os machos podem passar mais de dois meses sem comer enquanto enfrentam o inverno antártico."
  },
  {
    "id": "SCI-019",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Existem mais luas na Terra do que oceanos.",
    "opcaoB": "Existem mais vulcões em Marte do que árvores na Terra.",
    "opcaoC": "Existem mais desertos em África do que rios no mundo.",
    "opcaoD": "Existem mais árvores na Terra do que estrelas na Via Láctea.",
    "respostaCorreta": "D) Existem mais árvores na Terra do que estrelas na Via Láctea.",
    "curiosidade": "As estimativas apontam para cerca de 3 biliões (trillion em inglês) de árvores no planeta, enquanto a Via Láctea deverá ter entre 100 e 400 mil milhões de estrelas."
  },
  {
    "id": "SCI-020",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "As abelhas existiam antes dos dinossauros.",
    "opcaoB": "Os cavalos apareceram antes dos peixes.",
    "opcaoC": "Os tubarões são mais antigos do que as árvores.",
    "opcaoD": "Os humanos coexistiram com os tiranossauros.",
    "respostaCorreta": "C) Os tubarões são mais antigos do que as árvores.",
    "curiosidade": "Os primeiros tubarões surgiram há mais de 400 milhões de anos. As primeiras árvores apareceram dezenas de milhões de anos depois."
  },
  {
    "id": "SCI-021",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem um pénis em forma de saca-rolhas?",
    "opcaoA": "Ganso",
    "opcaoB": "Cisne",
    "opcaoC": "Pato",
    "opcaoD": "Peru",
    "respostaCorreta": "C) Pato",
    "curiosidade": "Algumas espécies de patos desenvolveram órgãos reprodutores em forma de espiral. Curiosamente, as fêmeas desenvolveram o trato reprodutor com curvas em sentido oposto, num verdadeiro exemplo de \"corrida evolutiva\" entre os sexos. 🤣 A evolução não brinca em serviço."
  },
  {
    "id": "SCI-022",
    "disciplina": "Ciência",
    "pergunta": "Qual destas partes do corpo produz a maior parte da cera dos ouvidos?",
    "opcaoA": "Glândulas do canal auditivo",
    "opcaoB": "Cartilagem da orelha",
    "opcaoC": "Lóbulo",
    "opcaoD": "Tímpano",
    "respostaCorreta": "A) Glândulas do canal auditivo",
    "curiosidade": "A cera protege o ouvido contra poeiras, fungos, bactérias e pequenos insetos. Sim... insetos."
  },
  {
    "id": "SCI-023",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais morre pouco tempo depois de acasalar?",
    "opcaoA": "Cavalo",
    "opcaoB": "Polvo",
    "opcaoC": "Leão",
    "opcaoD": "Coruja",
    "respostaCorreta": "B) Polvo",
    "curiosidade": "Nos polvos, os machos morrem pouco depois do acasalamento e muitas fêmeas morrem após protegerem os ovos durante semanas ou meses sem comer. Natureza: 10/10 em drama."
  },
  {
    "id": "SCI-024",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O sangue é azul dentro do corpo.",
    "opcaoB": "O coração fica do lado direito.",
    "opcaoC": "Os ossos são ocos.",
    "opcaoD": "Os humanos brilham no escuro.",
    "respostaCorreta": "D) Os humanos brilham no escuro.",
    "curiosidade": "O corpo humano emite uma luz extremamente fraca devido a processos metabólicos. É milhões de vezes mais fraca do que aquilo que o olho humano consegue ver."
  },
  {
    "id": "SCI-025",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais consegue mudar de sexo várias vezes ao longo da vida?",
    "opcaoA": "Lobo",
    "opcaoB": "Águia",
    "opcaoC": "Golfinho",
    "opcaoD": "Peixe-limpador-azul",
    "respostaCorreta": "D) Peixe-limpador-azul",
    "curiosidade": "Algumas espécies de peixes podem alternar entre macho e fêmea mais do que uma vez, dependendo da estrutura social do grupo."
  },
  {
    "id": "SCI-026",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O fígado nunca cresce.",
    "opcaoB": "O cérebro pesa menos que um limão.",
    "opcaoC": "O estômago produz ácido suficientemente forte para dissolver uma lâmina de barbear.",
    "opcaoD": "Os pulmões são músculos.",
    "respostaCorreta": "C) O estômago produz ácido suficientemente forte para dissolver uma lâmina de barbear.",
    "curiosidade": "O ácido do estômago é extremamente forte. Felizmente, o revestimento do estômago renova-se constantemente para evitar que ele se \"digira\" a si próprio."
  },
  {
    "id": "SCI-027",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais pratica sexo por prazer, e não apenas para reprodução?",
    "opcaoA": "Zebra",
    "opcaoB": "Golfinho",
    "opcaoC": "Girafa",
    "opcaoD": "Rinoceronte",
    "respostaCorreta": "B) Golfinho",
    "curiosidade": "Os golfinhos são uma das poucas espécies conhecidas que têm comportamentos sexuais ligados também ao prazer, às relações sociais e à brincadeira."
  },
  {
    "id": "SCI-028",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "Todos os seres humanos têm diamantes microscópicos no sangue.",
    "opcaoB": "Todos os seres humanos têm mercúrio no coração.",
    "opcaoC": "Todos os seres humanos têm pequenas quantidades de ouro no corpo.",
    "opcaoD": "Todos os seres humanos têm prata nos ossos.",
    "respostaCorreta": "C) Todos os seres humanos têm pequenas quantidades de ouro no corpo.",
    "curiosidade": "Existem vestígios de ouro distribuídos pelo organismo, mas em quantidades tão pequenas que seriam precisas dezenas de milhares de pessoas para obter apenas alguns gramas."
  },
  {
    "id": "SCI-029",
    "disciplina": "Ciência",
    "pergunta": "Qual destes animais tem uma fêmea cujo órgão sexual pode parecer um pénis?",
    "opcaoA": "Loba",
    "opcaoB": "Zebra",
    "opcaoC": "Leoa",
    "opcaoD": "Hiena-malhada",
    "respostaCorreta": "D) Hiena-malhada",
    "curiosidade": "As hienas-malhadas fêmeas têm um clítoris extremamente desenvolvido, uma característica rara entre os mamíferos e muito estudada pelos biólogos."
  },
  {
    "id": "SCI-030",
    "disciplina": "Ciência",
    "pergunta": "Qual destas afirmações é verdadeira?",
    "opcaoA": "O sémen humano não contém vitaminas.",
    "opcaoB": "O sémen é produzido apenas nos testículos.",
    "opcaoC": "O sémen humano contém várias proteínas diferentes.",
    "opcaoD": "O sémen é composto apenas por espermatozoides.",
    "respostaCorreta": "C) O sémen humano contém várias proteínas diferentes.",
    "curiosidade": "O sémen é um fluido complexo produzido por várias glândulas do aparelho reprodutor masculino. Contém mais de 200 proteínas diferentes, além de açúcares, minerais e enzimas."
  },
  {
    "id": "EST-001",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais provoca mais mortes humanas por ano?",
    "opcaoA": "Mosquito",
    "opcaoB": "Tubarão",
    "opcaoC": "Lobo",
    "opcaoD": "Leão",
    "respostaCorreta": "A) Mosquito",
    "curiosidade": "Os mosquitos transmitem doenças como a malária e a dengue, sendo responsáveis por centenas de milhares de mortes todos os anos."
  },
  {
    "id": "EST-002",
    "disciplina": "Estatística",
    "pergunta": "Qual destas passwords esteve durante anos entre as mais usadas no mundo?",
    "opcaoA": "ilovepizza",
    "opcaoB": "portugal123",
    "opcaoC": "superhomem",
    "opcaoD": "password",
    "respostaCorreta": "D) password",
    "curiosidade": "Todos os anos aparecem milhões de contas protegidas com \"password\", \"123456\" ou \"qwerty\". Sim... ainda em 2026."
  },
  {
    "id": "EST-003",
    "disciplina": "Estatística",
    "pergunta": "Qual destes músculos trabalha mais vezes ao longo de um dia normal?",
    "opcaoA": "Coração",
    "opcaoB": "Bíceps",
    "opcaoC": "Gémeos",
    "opcaoD": "Pescoço",
    "respostaCorreta": "A) Coração",
    "curiosidade": "O coração bate cerca de 100 mil vezes por dia, sem pausas."
  },
  {
    "id": "EST-004",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países consome, em média, mais café por habitante?",
    "opcaoA": "Portugal",
    "opcaoB": "Brasil",
    "opcaoC": "Itália",
    "opcaoD": "Finlândia",
    "respostaCorreta": "D) Finlândia",
    "curiosidade": "A Finlândia lidera regularmente os rankings mundiais de consumo de café por pessoa."
  },
  {
    "id": "EST-005",
    "disciplina": "Estatística",
    "pergunta": "Qual destes emojis é habitualmente o mais utilizado no mundo?",
    "opcaoA": "👍",
    "opcaoB": "😂",
    "opcaoC": "❤️",
    "opcaoD": "😎",
    "respostaCorreta": "B) 😂",
    "curiosidade": "O 😂 liderou durante anos os rankings globais de utilização, embora a ordem varie ligeiramente entre plataformas e anos."
  },
  {
    "id": "EST-006",
    "disciplina": "Estatística",
    "pergunta": "Qual destes líquidos é o mais consumido no mundo, a seguir à água?",
    "opcaoA": "Chá",
    "opcaoB": "Leite",
    "opcaoC": "Café",
    "opcaoD": "Refrigerantes",
    "respostaCorreta": "A) Chá",
    "curiosidade": "O chá é consumido diariamente por milhares de milhões de pessoas em praticamente todos os continentes."
  },
  {
    "id": "EST-007",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais dorme mais horas por dia, em média?",
    "opcaoA": "Preguiça",
    "opcaoB": "Coala",
    "opcaoC": "Gato",
    "opcaoD": "Panda",
    "respostaCorreta": "B) Coala",
    "curiosidade": "Os coalas podem dormir entre 18 e 22 horas por dia devido à dieta pobre em energia."
  },
  {
    "id": "EST-008",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais fusos horários?",
    "opcaoA": "Canadá",
    "opcaoB": "França",
    "opcaoC": "Rússia",
    "opcaoD": "Estados Unidos",
    "respostaCorreta": "B) França",
    "curiosidade": "Graças aos seus territórios ultramarinos, a França é frequentemente considerada o país com mais fusos horários."
  },
  {
    "id": "EST-009",
    "disciplina": "Estatística",
    "pergunta": "Qual destas redes sociais ultrapassou primeiro mil milhões de utilizadores?",
    "opcaoA": "TikTok",
    "opcaoB": "Facebook",
    "opcaoC": "Instagram",
    "opcaoD": "Snapchat",
    "respostaCorreta": "B) Facebook",
    "curiosidade": "O Facebook foi a primeira grande rede social a atingir esse marco histórico."
  },
  {
    "id": "EST-010",
    "disciplina": "Estatística",
    "pergunta": "Qual destes alimentos é o mais roubado em supermercados de todo o mundo?",
    "opcaoA": "Atum",
    "opcaoB": "Café",
    "opcaoC": "Queijo",
    "opcaoD": "Chocolate",
    "respostaCorreta": "C) Queijo",
    "curiosidade": "Parece brincadeira, mas vários estudos sobre perdas no retalho apontam o queijo como um dos produtos alimentares mais furtados no mundo, devido ao seu valor e facilidade de revenda."
  },
  {
    "id": "EST-011",
    "disciplina": "Estatística",
    "pergunta": "Qual destes desportos tem mais praticantes no mundo?",
    "opcaoA": "Ténis",
    "opcaoB": "Futebol",
    "opcaoC": "Basquetebol",
    "opcaoD": "Natação",
    "respostaCorreta": "B) Futebol",
    "curiosidade": "Estima-se que mais de 3 mil milhões de pessoas acompanhem ou pratiquem futebol regularmente."
  },
  {
    "id": "EST-012",
    "disciplina": "Estatística",
    "pergunta": "Qual destes vídeos foi o primeiro a ultrapassar os 10 mil milhões de visualizações no YouTube?",
    "opcaoA": "Despacito",
    "opcaoB": "Baby Shark",
    "opcaoC": "Shape of You",
    "opcaoD": "Gangnam Style",
    "respostaCorreta": "B) Baby Shark",
    "curiosidade": "\"Baby Shark\" tornou-se o vídeo mais visto da história do YouTube e foi o primeiro a ultrapassar a marca dos 10 mil milhões de visualizações."
  },
  {
    "id": "EST-013",
    "disciplina": "Estatística",
    "pergunta": "Qual destes mamíferos passa mais tempo a dormir por dia?",
    "opcaoA": "Morcego-castanho",
    "opcaoB": "Gato",
    "opcaoC": "Leão",
    "opcaoD": "Coala",
    "respostaCorreta": "A) Morcego-castanho",
    "curiosidade": "Algumas espécies de morcegos chegam a dormir cerca de 20 horas por dia."
  },
  {
    "id": "EST-014",
    "disciplina": "Estatística",
    "pergunta": "Qual destes alimentos é consumido em maior quantidade no mundo?",
    "opcaoA": "Massa",
    "opcaoB": "Batata",
    "opcaoC": "Pão",
    "opcaoD": "Arroz",
    "respostaCorreta": "D) Arroz",
    "curiosidade": "O arroz é a base alimentar de milhares de milhões de pessoas, sobretudo na Ásia."
  },
  {
    "id": "EST-015",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem a maior população?",
    "opcaoA": "Estados Unidos",
    "opcaoB": "Índia",
    "opcaoC": "Brasil",
    "opcaoD": "Rússia",
    "respostaCorreta": "B) Índia",
    "curiosidade": "A Índia ultrapassou a China como o país mais populoso do mundo."
  },
  {
    "id": "EST-016",
    "disciplina": "Estatística",
    "pergunta": "Qual destes objetos é mais perdido em hotéis?",
    "opcaoA": "Sapatos",
    "opcaoB": "Carregadores de telemóvel",
    "opcaoC": "Casacos",
    "opcaoD": "Carteiras",
    "respostaCorreta": "B) Carregadores de telemóvel",
    "curiosidade": "Os carregadores estão entre os objetos mais esquecidos em hotéis, precisamente porque costumam ficar ligados às tomadas. 🤣 Quem nunca..."
  },
  {
    "id": "EST-017",
    "disciplina": "Estatística",
    "pergunta": "Qual destes músculos é considerado o mais forte do corpo humano em termos de força exercida?",
    "opcaoA": "Língua",
    "opcaoB": "Bíceps",
    "opcaoC": "Masséter (mandíbula)",
    "opcaoD": "Gémeos",
    "respostaCorreta": "C) Masséter (mandíbula)",
    "curiosidade": "O masséter, usado para mastigar, consegue exercer uma enorme força de mordida."
  },
  {
    "id": "EST-018",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países produz mais queijo?",
    "opcaoA": "Suíça",
    "opcaoB": "Itália",
    "opcaoC": "França",
    "opcaoD": "Estados Unidos",
    "respostaCorreta": "D) Estados Unidos",
    "curiosidade": "Apesar da fama europeia, os Estados Unidos lideram há anos a produção mundial de queijo."
  },
  {
    "id": "EST-019",
    "disciplina": "Estatística",
    "pergunta": "Qual destes domínios é o mais visitado no mundo?",
    "opcaoA": "youtube.com",
    "opcaoB": "amazon.com",
    "opcaoC": "google.com",
    "opcaoD": "wikipedia.org",
    "respostaCorreta": "C) google.com",
    "curiosidade": "O Google continua a liderar os rankings globais de tráfego na internet."
  },
  {
    "id": "EST-020",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais mata mais seres humanos diretamente?",
    "opcaoA": "Tubarão",
    "opcaoB": "Hipopótamo",
    "opcaoC": "Crocodilo",
    "opcaoD": "Cobra",
    "respostaCorreta": "D) Cobra",
    "curiosidade": "As mordeduras de cobras venenosas causam dezenas de milhares de mortes por ano. Os tubarões, apesar da fama, provocam muito menos vítimas."
  },
  {
    "id": "EST-021",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais ilhas?",
    "opcaoA": "Indonésia",
    "opcaoB": "Filipinas",
    "opcaoC": "Japão",
    "opcaoD": "Suécia",
    "respostaCorreta": "D) Suécia",
    "curiosidade": "A Suécia tem cerca de 267 mil ilhas, embora apenas uma pequena parte seja habitada."
  },
  {
    "id": "EST-022",
    "disciplina": "Estatística",
    "pergunta": "Qual destas empresas vende mais consolas de videojogos?",
    "opcaoA": "Sony",
    "opcaoB": "Microsoft",
    "opcaoC": "Nintendo",
    "opcaoD": "Sega",
    "respostaCorreta": "A) Sony",
    "curiosidade": "Com a família PlayStation, a Sony tornou-se a fabricante de consolas domésticas mais bem-sucedida da história."
  },
  {
    "id": "EST-023",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países produz mais vinho?",
    "opcaoA": "França",
    "opcaoB": "Itália",
    "opcaoC": "Portugal",
    "opcaoD": "Espanha",
    "respostaCorreta": "B) Itália",
    "curiosidade": "A liderança alterna entre Itália e França consoante o ano, mas Itália ocupa frequentemente o primeiro lugar na produção mundial."
  },
  {
    "id": "EST-024",
    "disciplina": "Estatística",
    "pergunta": "Qual destes produtos é mais roubado em hotéis?",
    "opcaoA": "Toalhas",
    "opcaoB": "Comandos da televisão",
    "opcaoC": "Copos",
    "opcaoD": "Almofadas",
    "respostaCorreta": "A) Toalhas",
    "curiosidade": "As toalhas continuam entre os objetos mais levados pelos hóspedes. Sim... há quem ache que estão incluídas no preço."
  },
  {
    "id": "EST-025",
    "disciplina": "Estatística",
    "pergunta": "Qual destas aplicações é descarregada mais vezes no mundo?",
    "opcaoA": "Discord",
    "opcaoB": "Spotify",
    "opcaoC": "TikTok",
    "opcaoD": "WhatsApp",
    "respostaCorreta": "D) WhatsApp",
    "curiosidade": "O WhatsApp mantém-se entre as aplicações mais descarregadas e utilizadas globalmente, graças à enorme base de utilizadores."
  },
  {
    "id": "EST-026",
    "disciplina": "Estatística",
    "pergunta": "Qual destas coisas acontece mais vezes durante um dia normal?",
    "opcaoA": "Engolir",
    "opcaoB": "Pestanejar",
    "opcaoC": "Bocejar",
    "opcaoD": "Espirrar",
    "respostaCorreta": "B) Pestanejar",
    "curiosidade": "Uma pessoa pode pestanejar entre 15 e 20 mil vezes por dia, quase sem dar por isso."
  },
  {
    "id": "EST-027",
    "disciplina": "Estatística",
    "pergunta": "Qual destes animais vive, em média, mais tempo?",
    "opcaoA": "Crocodilo",
    "opcaoB": "Elefante",
    "opcaoC": "Tartaruga-gigante",
    "opcaoD": "Baleia-azul",
    "respostaCorreta": "C) Tartaruga-gigante",
    "curiosidade": "Algumas tartarugas-gigantes ultrapassam os 180 anos, tornando-se dos vertebrados mais longevos conhecidos."
  },
  {
    "id": "EST-028",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países consome mais chocolate por pessoa?",
    "opcaoA": "Reino Unido",
    "opcaoB": "Bélgica",
    "opcaoC": "Alemanha",
    "opcaoD": "Suíça",
    "respostaCorreta": "D) Suíça",
    "curiosidade": "A Suíça está regularmente entre os países com maior consumo de chocolate por habitante."
  },
  {
    "id": "EST-029",
    "disciplina": "Estatística",
    "pergunta": "Qual destes idiomas tem mais falantes nativos?",
    "opcaoA": "Inglês",
    "opcaoB": "Espanhol",
    "opcaoC": "Hindi",
    "opcaoD": "Mandarim",
    "respostaCorreta": "D) Mandarim",
    "curiosidade": "O mandarim é a língua com mais falantes nativos do planeta, muito à frente do inglês."
  },
  {
    "id": "EST-030",
    "disciplina": "Estatística",
    "pergunta": "Qual destes países tem mais pirâmides?",
    "opcaoA": "Egito",
    "opcaoB": "Sudão",
    "opcaoC": "México",
    "opcaoD": "Peru",
    "respostaCorreta": "B) Sudão",
    "curiosidade": "O Sudão possui mais de 200 pirâmides, ultrapassando largamente o Egito. Foram construídas pelo antigo Reino de Cuxe."
  },
  {
    "id": "POP-001",
    "disciplina": "Cultura & Caos",
    "pergunta": "Como se chamava originalmente o Mario quando apareceu pela primeira vez?",
    "opcaoA": "Luigi",
    "opcaoB": "Mr. Nintendo",
    "opcaoC": "Plumber Joe",
    "opcaoD": "Jumpman",
    "respostaCorreta": "D) Jumpman",
    "curiosidade": "Na sua estreia em Donkey Kong (1981), Mario era apenas conhecido por Jumpman. O nome \"Mario\" surgiu mais tarde, inspirado num senhorio dos escritórios da Nintendo of America."
  },
  {
    "id": "POP-002",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes atores recusou interpretar Neo em The Matrix?",
    "opcaoA": "Tom Cruise",
    "opcaoB": "Brad Pitt",
    "opcaoC": "Keanu Reeves",
    "opcaoD": "Will Smith",
    "respostaCorreta": "D) Will Smith",
    "curiosidade": "Will Smith recusou o papel porque não percebeu bem o argumento. Acabou por fazer Wild Wild West... uma decisão que ele próprio já admitiu arrepender-se de ter tomado."
  },
  {
    "id": "POP-003",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes jogos foi proibido em vários países devido ao nível de violência?",
    "opcaoA": "The Sims",
    "opcaoB": "Manhunt 2",
    "opcaoC": "Rocket League",
    "opcaoD": "Minecraft",
    "respostaCorreta": "B) Manhunt 2",
    "curiosidade": "Manhunt 2 foi proibido ou censurado em vários países, tornando-se um dos videojogos mais controversos da sua época."
  },
  {
    "id": "POP-004",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes memes nasceu de uma fotografia verdadeira?",
    "opcaoA": "Rage Guy",
    "opcaoB": "Trollface",
    "opcaoC": "Wojak",
    "opcaoD": "Disaster Girl",
    "respostaCorreta": "D) Disaster Girl",
    "curiosidade": "A fotografia da \"Disaster Girl\" mostra uma menina real a sorrir enquanto uma casa arde ao fundo durante um treino controlado dos bombeiros."
  },
  {
    "id": "POP-005",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes filmes ganhou 11 Óscares?",
    "opcaoA": "Barbie",
    "opcaoB": "Joker",
    "opcaoC": "Titanic",
    "opcaoD": "Avatar",
    "respostaCorreta": "C) Titanic",
    "curiosidade": "Titanic igualou o recorde de 11 Óscares, feito que também pertence a Ben-Hur e O Senhor dos Anéis: O Regresso do Rei."
  },
  {
    "id": "POP-006",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas personagens da Nintendo nem sequer foi criada para ser protagonista?",
    "opcaoA": "Kirby",
    "opcaoB": "Mario",
    "opcaoC": "Samus",
    "opcaoD": "Link",
    "respostaCorreta": "B) Mario",
    "curiosidade": "Mario nasceu apenas como personagem principal de Donkey Kong. A Nintendo nunca imaginou que se tornaria a cara da empresa durante décadas."
  },
  {
    "id": "POP-007",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas séries terminou com uma petição online para refazer a última temporada?",
    "opcaoA": "Game of Thrones",
    "opcaoB": "Breaking Bad",
    "opcaoC": "Friends",
    "opcaoD": "The Office",
    "respostaCorreta": "A) Game of Thrones",
    "curiosidade": "Mais de um milhão de pessoas assinaram uma petição a pedir que a oitava temporada fosse refeita. 🤣 A malta ficou mesmo aziada."
  },
  {
    "id": "POP-008",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas músicas é atualmente uma das mais reproduzidas de sempre no Spotify?",
    "opcaoA": "Gangnam Style",
    "opcaoB": "Bohemian Rhapsody",
    "opcaoC": "Blinding Lights",
    "opcaoD": "Wonderwall",
    "respostaCorreta": "C) Blinding Lights",
    "curiosidade": "A música de The Weeknd tornou-se a faixa mais reproduzida da história da plataforma."
  },
  {
    "id": "POP-009",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas plataformas nasceu originalmente como um site de encontros?",
    "opcaoA": "Facebook",
    "opcaoB": "Reddit",
    "opcaoC": "YouTube",
    "opcaoD": "Discord",
    "respostaCorreta": "C) YouTube",
    "curiosidade": "Os fundadores imaginaram o YouTube como um site onde as pessoas podiam carregar vídeos para se apresentarem a potenciais parceiros. A ideia não pegou... e decidiram abrir a plataforma a todo o tipo de vídeos."
  },
  {
    "id": "POP-010",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas personagens de videojogos é canonicamente mais velha?",
    "opcaoA": "Crash Bandicoot",
    "opcaoB": "Pac-Man",
    "opcaoC": "Sonic",
    "opcaoD": "Master Chief",
    "respostaCorreta": "B) Pac-Man",
    "curiosidade": "Pac-Man nasceu em 1980, tornando-se uma das personagens mais antigas e icónicas da história dos videojogos."
  },
  {
    "id": "POP-011",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase? \"É 'piners' para nós.\"",
    "opcaoA": "Toni",
    "opcaoB": "Fernando Santos",
    "opcaoC": "Jorge Jesus",
    "opcaoD": "José Mourinho",
    "respostaCorreta": "C) Jorge Jesus",
    "curiosidade": "Esta foi dita em 2014, na antecipação de um jogo com o Guimarães, quando falava da pressão sentida pelos jogadores. Tornou-se uma das expressões mais repetidas nos memes de futebol português."
  },
  {
    "id": "POP-012",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes programas continua há mais anos consecutivos no ar?",
    "opcaoA": "Praça da Alegria",
    "opcaoB": "Big Show SIC",
    "opcaoC": "Você na TV",
    "opcaoD": "Preço Certo",
    "respostaCorreta": "D) Preço Certo",
    "curiosidade": "O Preço Certo estreou em Portugal em 2002 com Fernando Mendes e continua a ser um dos programas mais vistos da televisão portuguesa."
  },
  {
    "id": "POP-013",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas frases nasceu mesmo de um momento televisivo?",
    "opcaoA": "\"É lidar, irmoum.\"",
    "opcaoB": "\"Tá bonito, tá.\"",
    "opcaoC": "\"É uma maravilha.\"",
    "opcaoD": "\"Ai Jesus!\"",
    "respostaCorreta": "C) \"É uma maravilha.\"",
    "curiosidade": "Fernando Mendes transformou várias expressões espontâneas em autênticos memes nacionais."
  },
  {
    "id": "POP-014",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes memes nasceu de uma fotografia tirada num treino dos bombeiros?",
    "opcaoA": "Success Kid",
    "opcaoB": "Bad Luck Brian",
    "opcaoC": "Disaster Girl",
    "opcaoD": "Hide the Pain Harold",
    "respostaCorreta": "C) Disaster Girl",
    "curiosidade": "A casa estava a ser queimada de forma controlada. A fotografia da pequena Zoe tornou-se um dos memes mais famosos da internet."
  },
  {
    "id": "POP-015",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente \"Se eu falar, tenho grandes problemas\" numa entrevista?",
    "opcaoA": "Rui Vitória",
    "opcaoB": "Fernando Santos",
    "opcaoC": "Paulo Bento",
    "opcaoD": "José Mourinho",
    "respostaCorreta": "D) José Mourinho",
    "curiosidade": "Frase real dita em inglês (\"If I speak, I am in big trouble\"), em março de 2014, após o Chelsea perder com o Aston Villa. Tornou-se um dos memes de futebol mais duradouros da internet."
  },
  {
    "id": "POP-016",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes sons foi gravado usando um porco-da-índia?",
    "opcaoA": "Sonic",
    "opcaoB": "Pokémon",
    "opcaoC": "Donkey Kong",
    "opcaoD": "Yoshi",
    "respostaCorreta": "D) Yoshi",
    "curiosidade": "A voz do Yoshi é a própria voz do compositor Kazumi Totaka, gravada e depois manipulada eletronicamente (acelerada/alterada num sintetizador) — não é gravação de nenhum animal."
  },
  {
    "id": "POP-017",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes apresentadores apresenta o Preço Certo desde o primeiro episódio português?",
    "opcaoA": "Herman José",
    "opcaoB": "Fernando Mendes",
    "opcaoC": "João Baião",
    "opcaoD": "José Figueiras",
    "respostaCorreta": "B) Fernando Mendes",
    "curiosidade": "É uma das carreiras mais longas da televisão portuguesa no mesmo formato."
  },
  {
    "id": "POP-018",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas plataformas tornou famosa a expressão \"Rickroll\"?",
    "opcaoA": "Twitch",
    "opcaoB": "Facebook",
    "opcaoC": "YouTube",
    "opcaoD": "Reddit",
    "respostaCorreta": "C) YouTube",
    "curiosidade": "O Rickroll espalhou-se através do YouTube, onde milhões de pessoas eram enganadas para abrir o videoclip de Never Gonna Give You Up."
  },
  {
    "id": "POP-019",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase? \"Um treinador não tem passado nem futuro, só tem passado.\"",
    "opcaoA": "Toni",
    "opcaoB": "Jorge Jesus",
    "opcaoC": "Manuel Machado",
    "opcaoD": "Mourinho",
    "respostaCorreta": "B) Jorge Jesus",
    "curiosidade": "Frase real e documentada, chegou a ser título de um artigo do Correio da Manhã sobre as frases mais marcantes de Jorge Jesus."
  },
  {
    "id": "POP-020",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas pessoas ficou conhecida em Portugal por gritar repetidamente... \"Olhó avião!\"",
    "opcaoA": "Fernando Mendes",
    "opcaoB": "Emanuel",
    "opcaoC": "Toy",
    "opcaoD": "Batatinha",
    "respostaCorreta": "C) Toy",
    "curiosidade": "A expressão tornou-se inseparável dos concertos do Toy e acabou por entrar no vocabulário popular."
  },
  {
    "id": "POP-021",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem disse realmente esta frase? \"Perdemos porque o adversário marcou mais golos.\"",
    "opcaoA": "Nenhum treinador português disse esta frase — é um meme da internet.",
    "opcaoB": "Manuel Machado",
    "opcaoC": "João Pinto",
    "opcaoD": "Jorge Jesus",
    "respostaCorreta": "A) Nenhum treinador português disse esta frase — é um meme da internet.",
    "curiosidade": "Apesar de parecer uma frase saída de uma conferência de imprensa, nenhum destes treinadores portugueses a disse realmente. É um daqueles \"memes\" que a internet acabou por transformar em verdade. especificado \"nenhum treinador português\" (em vez de \"nenhum treinador real\", mais amplo) — evita a pergunta ficar vulnerável a uma atribuição a alguém fora da lista/categoria. 🤣 Adoro este tipo de pergunta porque apanha toda a gente."
  },
  {
    "id": "POP-022",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes programas portugueses usava realmente um famoso telefone vermelho?",
    "opcaoA": "Big Brother",
    "opcaoB": "1 Contra Todos",
    "opcaoC": "Big Show SIC",
    "opcaoD": "Preço Certo",
    "respostaCorreta": "A) Big Brother",
    "curiosidade": "O telefone vermelho icónico é do Big Brother — toca para desafios e anúncios especiais aos concorrentes, um elemento recorrente e muito reconhecível do formato."
  },
  {
    "id": "POP-023",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas frases nasceu de uma publicidade e ficou famosa em Portugal?",
    "opcaoA": "\"É só fazer as contas.\"",
    "opcaoB": "\"Há mar e mar...\"",
    "opcaoC": "\"Falta-te um bocadinho assim.\"",
    "opcaoD": "\"É um espetáculo!\"",
    "respostaCorreta": "C) \"Falta-te um bocadinho assim.\"",
    "curiosidade": "A frase nasceu dos anúncios do iogurte Danoninho, no início dos anos 2000, sempre acompanhada do gesto de mão a mostrar o \"tamanho\" do bocadinho. Ainda hoje é reconhecida por muita gente."
  },
  {
    "id": "POP-024",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes treinadores ficou particularmente conhecido pelas suas \"jesuadas\", trocando frequentemente palavras e expressões?",
    "opcaoA": "Carlos Queiroz",
    "opcaoB": "Paulo Bento",
    "opcaoC": "Fernando Santos",
    "opcaoD": "Jorge Jesus",
    "respostaCorreta": "D) Jorge Jesus",
    "curiosidade": "As conferências de Jorge Jesus deram origem a dezenas de páginas, vídeos e compilações de frases memoráveis."
  },
  {
    "id": "POP-025",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes youtubers portugueses começou por fazer vídeos de Minecraft?",
    "opcaoA": "Wuant",
    "opcaoB": "Tiagovski",
    "opcaoC": "Numeiro",
    "opcaoD": "Windoh",
    "respostaCorreta": "B) Tiagovski",
    "curiosidade": "Tiagovski é um dos primeiros youtubers portugueses de gaming, com atividade desde 2010, tendo começado por conteúdo de Minecraft antes de expandir para outros jogos."
  },
  {
    "id": "POP-026",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes apresentadores é conhecido como \"O Gordo\" em inúmeros memes da internet portuguesa?",
    "opcaoA": "Goucha",
    "opcaoB": "Baião",
    "opcaoC": "Malato",
    "opcaoD": "Fernando Mendes",
    "respostaCorreta": "D) Fernando Mendes",
    "curiosidade": "É um termo carinhoso, nunca ofensivo, usado com afeto pelo público. Nos últimos anos, Fernando Mendes emagreceu bastante por motivos de saúde — o apelido ficou como memória de uma imagem antiga, não da atual."
  },
  {
    "id": "POP-027",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes artistas ficou conhecido pela frase... \"Olhó avião!\"",
    "opcaoA": "Quim Barreiros",
    "opcaoB": "Toy",
    "opcaoC": "Emanuel",
    "opcaoD": "Nel Monteiro",
    "respostaCorreta": "B) Toy",
    "curiosidade": "É praticamente impossível ouvir esta expressão sem pensar imediatamente num concerto do Toy."
  },
  {
    "id": "POP-028",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quem ficou famoso, em Portugal, por se orgulhar de conduzir a 120 km/h usando só os joelhos?",
    "opcaoA": "Quim Barreiros",
    "opcaoB": "Ruy de Carvalho",
    "opcaoC": "Toy",
    "opcaoD": "Marco Paulo",
    "respostaCorreta": "C) Toy",
    "curiosidade": "No seu reality show \"Na Casa do Toy\" (SIC, 2002), o cantor mostrava-se a conduzir usando os joelhos para ter as mãos livres. Décadas depois, ainda é lembrado por isso — inclusive por outros artistas em entrevistas."
  },
  {
    "id": "POP-029",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes concursos ficou famoso por oferecer... um automóvel em praticamente todos os programas?",
    "opcaoA": "Chuva de Estrelas",
    "opcaoB": "A Roda da Sorte",
    "opcaoC": "Preço Certo",
    "opcaoD": "Quem Quer Ser Milionário?",
    "respostaCorreta": "C) Preço Certo",
    "curiosidade": "O momento da revelação do automóvel tornou-se um clássico da televisão portuguesa."
  },
  {
    "id": "POP-030",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas expressões foi realmente dita por Jorge Jesus?",
    "opcaoA": "\"O futebol não é só correr, para correr há o atletismo.\"",
    "opcaoB": "\"Não somos favoritos, somos favoritados.\"",
    "opcaoC": "\"O importante é marcar mais golos do que o adversário.\"",
    "opcaoD": "\"O empate é uma vitória sem ganhar.\"",
    "respostaCorreta": "A) \"O futebol não é só correr, para correr há o atletismo.\"",
    "curiosidade": "Frase trocada por outra genuína de Jorge Jesus. Jorge Jesus deixou dezenas de expressões únicas ao longo da carreira. Algumas parecem inventadas... mas foram mesmo ditas."
  },
  {
    "id": "POP-031",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes eventos aconteceu mesmo, envolvendo o Cristiano Ronaldo?",
    "opcaoA": "Pediu para o filho nascer no dia do seu aniversário",
    "opcaoB": "Uma estátua sua no Aeroporto da Madeira foi tão criticada que teve de ser substituída",
    "opcaoC": "Recusou-se a jogar por Portugal durante um ano",
    "opcaoD": "Foi expulso de um jogo da seleção por insultar o árbitro",
    "respostaCorreta": "B) Uma estátua sua no Aeroporto da Madeira foi tão criticada que teve de ser substituída",
    "curiosidade": "A escultura original, feita pelo artista Emanuel Santos e revelada em 2017, tornou-se viral por não se parecer nada com o jogador — chegou a ser comparada ao ex-futebolista irlandês Niall Quinn. Foi substituída em 2018, a pedido da família de Ronaldo."
  },
  {
    "id": "POP-032",
    "disciplina": "Cultura & Caos",
    "pergunta": "Em que posição ficou Portugal na Eurovisão antes de, finalmente, vencer o festival pela primeira vez, em 2017?",
    "opcaoA": "Portugal nunca tinha sequer chegado ao top 5 em mais de 50 participações",
    "opcaoB": "Em 3º lugar, em 2010",
    "opcaoC": "Portugal já tinha vencido antes, em 1994",
    "opcaoD": "Em 2º lugar, em 2016",
    "respostaCorreta": "A) Portugal nunca tinha sequer chegado ao top 5 em mais de 50 participações",
    "curiosidade": "Salvador Sobral venceu com \"Amar Pelos Dois\" (escrita pela irmã, Luísa Sobral), com 758 pontos — a maior pontuação de sempre na história do festival. Foi a primeira vitória portuguesa em mais de 50 anos de participações."
  },
  {
    "id": "POP-033",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quantos Prémios Nobel de Literatura já ganhou Portugal?",
    "opcaoA": "Um, José Saramago em 1998",
    "opcaoB": "Nenhum",
    "opcaoC": "Três",
    "opcaoD": "Dois",
    "respostaCorreta": "A) Um, José Saramago em 1998",
    "curiosidade": "José Saramago continua a ser o único autor de língua portuguesa a vencer o Nobel da Literatura, em 1998. Portugal só tem mais um Nobel — o de Medicina, ganho por Egas Moniz em 1949."
  },
  {
    "id": "POP-034",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual foi a primeira expressão artística portuguesa a ser declarada Património Cultural Imaterial da Humanidade pela UNESCO?",
    "opcaoA": "A Guitarra Portuguesa",
    "opcaoB": "O Cante Alentejano",
    "opcaoC": "O Vira (dança popular)",
    "opcaoD": "O Fado",
    "respostaCorreta": "D) O Fado",
    "curiosidade": "O Fado foi reconhecido pela UNESCO em novembro de 2011. O Cante Alentejano só viria a ser reconhecido 3 anos depois, em 2014."
  },
  {
    "id": "POP-035",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quantas pessoas sabem, ao certo, a receita secreta original dos Pastéis de Belém?",
    "opcaoA": "Só a família fundadora, ninguém mais",
    "opcaoB": "Uma única pessoa, sempre",
    "opcaoC": "Cerca de 100, uma em cada loja",
    "opcaoD": "Um grupo restrito de 6 a 8 pessoas",
    "respostaCorreta": "D) Um grupo restrito de 6 a 8 pessoas",
    "curiosidade": "A massa e o creme são preparados todos os dias na chamada \"Sala do Segredo\", por 3 mestres pasteleiros e os gerentes da casa. Todos assinam um contrato de confidencialidade."
  },
  {
    "id": "POP-036",
    "disciplina": "Cultura & Caos",
    "pergunta": "Em que década começaram as primeiras emissões regulares de televisão em Portugal, pela RTP?",
    "opcaoA": "Anos 1960",
    "opcaoB": "Anos 1970",
    "opcaoC": "Anos 1940",
    "opcaoD": "Anos 1950",
    "respostaCorreta": "D) Anos 1950",
    "curiosidade": "A RTP fez a primeira emissão experimental em 1956 e começou emissões regulares em 1957, tornando Portugal um dos primeiros países da Europa a ter televisão pública."
  },
  {
    "id": "POP-037",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas obras é o poema épico mais famoso da literatura portuguesa, escrito por Luís de Camões?",
    "opcaoA": "Os Lusíadas",
    "opcaoB": "Auto da Barca do Inferno",
    "opcaoC": "O Ano da Morte de Ricardo Reis",
    "opcaoD": "Mensagem",
    "respostaCorreta": "A) Os Lusíadas",
    "curiosidade": "\"Os Lusíadas\" foi publicado em 1572 e narra as viagens marítimas portuguesas, sobretudo a de Vasco da Gama até à Índia. \"Mensagem\" é de Fernando Pessoa, não de Camões."
  },
  {
    "id": "POP-038",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas localidades portuguesas é oficialmente o local da maior onda alguma vez surfada no mundo?",
    "opcaoA": "Costa da Caparica",
    "opcaoB": "Peniche",
    "opcaoC": "Nazaré",
    "opcaoD": "Ericeira",
    "respostaCorreta": "C) Nazaré",
    "curiosidade": "É na Praia do Norte, na Nazaré, que os recordes mundiais de ondas gigantes se sucedem desde 2011 — já passaram por lá Garrett McNamara, Rodrigo Koxa e o atual recordista, o alemão Sebastian Steudtner (26,21 metros, em 2020)."
  },
  {
    "id": "POP-039",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual foi o primeiro Prémio Nobel alguma vez atribuído a um português?",
    "opcaoA": "Medicina, a Egas Moniz",
    "opcaoB": "Paz, a um diplomata português",
    "opcaoC": "Literatura, a José Saramago",
    "opcaoD": "Química, a um investigador de Coimbra",
    "respostaCorreta": "A) Medicina, a Egas Moniz",
    "curiosidade": "Egas Moniz venceu o Nobel da Medicina em 1949 pela invenção da leucotomia pré-frontal (mais tarde popularizada, de forma controversa, como \"lobotomia\"). Só quase 50 anos depois, em 1998, Portugal teve o seu 2º Nobel, com José Saramago."
  },
  {
    "id": "POP-040",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destes momentos caricatos aconteceu mesmo, ao vivo, na televisão?",
    "opcaoA": "Um pivô da RTP confundiu o Papa com um ator",
    "opcaoB": "Um convidado adormeceu em direto num debate",
    "opcaoC": "Um repórter apresentou o tempo com o mapa ao contrário durante 5 minutos",
    "opcaoD": "Um jornalista francês entrevistou o Presidente de Portugal sem saber quem ele era",
    "respostaCorreta": "D) Um jornalista francês entrevistou o Presidente de Portugal sem saber quem ele era",
    "curiosidade": "Aconteceu na Assembleia-Geral da ONU, em 2016: o jornalista Martin Weill entrevistou Marcelo Rebelo de Sousa sem fazer ideia de que estava a falar com o Presidente da República Portuguesa. O vídeo tornou-se viral."
  },
  {
    "id": "POP-041",
    "disciplina": "Cultura & Caos",
    "pergunta": "O que aconteceu a uma concorrente do \"Preço Certo\" ao ficar cara a cara com o apresentador Fernando Mendes?",
    "opcaoA": "Desmaiou de emoção em direto",
    "opcaoB": "Recusou-se a jogar e foi embora",
    "opcaoC": "Ficou quase 2 minutos a rir sem conseguir falar",
    "opcaoD": "Confundiu-o com outro apresentador da RTP",
    "respostaCorreta": "C) Ficou quase 2 minutos a rir sem conseguir falar",
    "curiosidade": "A concorrente Anailde ficou tão nervosa e feliz que passou quase dois minutos inteiros a rir sem parar, sem conseguir dizer nada, até finalmente confessar: \"Senhor Fernando Mendes, nunca imaginei estar ao pé de si.\""
  },
  {
    "id": "POP-042",
    "disciplina": "Cultura & Caos",
    "pergunta": "Como se chama, mesmo, a \"bruma íntima\" que a Cristina Ferreira lançou em 2025?",
    "opcaoA": "ÍNTIMA",
    "opcaoB": "PIPY",
    "opcaoC": "FRESCA",
    "opcaoD": "GIRA",
    "respostaCorreta": "B) PIPY",
    "curiosidade": "O produto gerou polémica nas redes sociais e até farmacêuticas vieram alertar sobre riscos de perfumes na zona íntima. Cristina Ferreira defendeu-se dizendo que era uma \"provocação\" do seu novo projeto, o #euSouGIRA."
  },
  {
    "id": "POP-043",
    "disciplina": "Cultura & Caos",
    "pergunta": "Na primeira edição do \"Big Brother\" português, em 2000, o que aconteceu que chegou a ofuscar nos telejornais o anúncio da recandidatura do Presidente Jorge Sampaio?",
    "opcaoA": "A casa ficou às escuras durante 3 dias",
    "opcaoB": "Um concorrente deu um pontapé a uma colega, e foi expulso",
    "opcaoC": "Um concorrente fugiu da casa a nado",
    "opcaoD": "Dois concorrentes casaram-se em direto",
    "respostaCorreta": "B) Um concorrente deu um pontapé a uma colega, e foi expulso",
    "curiosidade": "Marco Borges deu um pontapé na barriga a Sónia Veiga durante uma discussão, no 47º dia da competição. O episódio abriu o \"Jornal Nacional\" da TVI, relegando a notícia política para segundo plano."
  },
  {
    "id": "POP-044",
    "disciplina": "Cultura & Caos",
    "pergunta": "No famoso meme \"Juro, Joca\", o que aconteceu realmente ao Joca depois do amigo jurar que o salto do telhado \"não doía\"?",
    "opcaoA": "Caiu de cara no chão",
    "opcaoB": "Partiu um braço a sério",
    "opcaoC": "Não se magoou nada",
    "opcaoD": "Recusou-se a saltar",
    "respostaCorreta": "A) Caiu de cara no chão",
    "curiosidade": "O vídeo é de 2011, gravado em Guimarães por Miguel Matos (quem salta primeiro e diz a frase) e João Neves, o \"Joca\". Em 2025, a operadora NOS reuniu os dois, agora adultos, para recriar o salto num anúncio."
  },
  {
    "id": "POP-045",
    "disciplina": "Cultura & Caos",
    "pergunta": "Porque é que a RTP deixou de exibir \"Os Cavaleiros do Zodíaco\", pouco depois de o estrear em 1992?",
    "opcaoA": "Queixas de pais devido à violência da série",
    "opcaoB": "Trocaram por Dragon Ball Z",
    "opcaoC": "O canal fechou a estação de dobragem",
    "opcaoD": "A licença dos direitos acabou",
    "respostaCorreta": "A) Queixas de pais devido à violência da série",
    "curiosidade": "A série estreou aos sábados de manhã, legendada em japonês, mas só chegou a passar 36 episódios. Fruto do sucesso do Dragon Ball Z, a SIC \"repescou-a\" em 1998, já dobrada — mas nunca chegou a exibir o episódio 37, por razões que continuam por explicar."
  },
  {
    "id": "POP-046",
    "disciplina": "Cultura & Caos",
    "pergunta": "Como se chamava, em Portugal nos anos 90, a série que hoje conhecemos como \"Sailor Moon\"?",
    "opcaoA": "Guerreiras da Lua",
    "opcaoB": "Navegantes da Lua",
    "opcaoC": "Princesas do Cosmos",
    "opcaoD": "As Meninas Mágicas",
    "respostaCorreta": "B) Navegantes da Lua",
    "curiosidade": "A SIC traduziu o título original japonês (\"Bishōjo Senshi Sailor Moon\") como \"Navegantes da Lua\" quando a série estreou em Portugal, na década de 1990."
  },
  {
    "id": "POP-047",
    "disciplina": "Cultura & Caos",
    "pergunta": "Qual destas instituições portuguesas chegou a suspender aulas para os alunos poderem ver \"Dragon Ball Z\"?",
    "opcaoA": "Universidade de Coimbra",
    "opcaoB": "Academia Militar",
    "opcaoC": "Instituto Superior Técnico",
    "opcaoD": "Escola Naval",
    "respostaCorreta": "C) Instituto Superior Técnico",
    "curiosidade": "Durante o auge do fenómeno, em 1997, várias escolas e instituições paravam atividades para os alunos verem episódios sem faltar às aulas — o caso do Instituto Superior Técnico foi o mais mediático de todos."
  },
  {
    "id": "POP-048",
    "disciplina": "Cultura & Caos",
    "pergunta": "No desenho animado \"Dartacão e os Três Moscãoteiros\", que passava na RTP, qual era o género de todas as personagens principais?",
    "opcaoA": "Eram todas humanos normais",
    "opcaoB": "Eram todas robôs",
    "opcaoC": "Eram todas cães",
    "opcaoD": "Eram todas gatos",
    "respostaCorreta": "C) Eram todas cães",
    "curiosidade": "Esta adaptação de \"Os Três Mosqueteiros\" de Alexandre Dumas, coproduzida por Espanha e Japão, transformou D'Artagnan e companhia em cães antropomórficos — mantendo a história de capa e espada quase igual ao livro original."
  },
  {
    "id": "POP-049",
    "disciplina": "Cultura & Caos",
    "pergunta": "Os nomes das 4 Tartarugas Ninja (Leonardo, Rafael, Miguel Ângelo e Donatello) foram todos escolhidos em homenagem a quê?",
    "opcaoA": "Imperadores romanos",
    "opcaoB": "Filósofos gregos",
    "opcaoC": "Astronautas da NASA",
    "opcaoD": "Artistas do Renascimento italiano",
    "respostaCorreta": "D) Artistas do Renascimento italiano",
    "curiosidade": "O mestre Splinter batizou cada tartaruga com o nome de um grande artista renascentista — Leonardo da Vinci, Rafael Sanzio, Michelangelo Buonarroti e Donatello."
  },
  {
    "id": "POP-050",
    "disciplina": "Cultura & Caos",
    "pergunta": "Quantos episódios da série \"Pokémon\" nunca chegaram a ser exibidos em Portugal, por terem sido banidos?",
    "opcaoA": "Uma temporada inteira",
    "opcaoB": "3 episódios",
    "opcaoC": "10 episódios",
    "opcaoD": "Nenhum, passaram todos",
    "respostaCorreta": "B) 3 episódios",
    "curiosidade": "Os episódios 18, 35 e 38 foram banidos e nunca passaram em Portugal nem na maioria dos países ocidentais — o mais famoso deles ficou conhecido por ter provocado convulsões em centenas de crianças no Japão, devido a uma sequência de luzes estroboscópicas."
  }
];
